[package]
name = "perpustakaan-desktop"
version = "1.0.7"
description = "Perpustakaan Nusantara v2 desktop (Tauri 2)"
authors = ["alvi arts"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "perpustakaan_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.2", features = ["tray-icon", "image-png", "protocol-asset"] }
tauri-plugin-dialog = "2.2"
tauri-plugin-fs = "2.2"
tauri-plugin-shell = "2.2"
tauri-plugin-sql = { version = "2.2", features = ["sqlite"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
bcrypt = "0.16"
rusqlite = { version = "0.32", features = ["bundled"] }
directories = "5"
log = "0.4"
env_logger = "0.11"
rand = "0.8"
hex = "0.4"
chrono = { version = "0.4", features = ["clock"] }
sha2 = "0.10"
base64 = "0.22"
opener = "0.7"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "bmp", "webp"] }

[dev-dependencies]
tempfile = "3"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
