/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedLaporanRouteImport } from './routes/_authed/laporan'
import { Route as AuthedKunjunganRouteImport } from './routes/_authed/kunjungan'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedPengembalianIndexRouteImport } from './routes/_authed/pengembalian/index'
import { Route as AuthedPeminjamanIndexRouteImport } from './routes/_authed/peminjaman/index'
import { Route as AuthedLaporanIndexRouteImport } from './routes/_authed/laporan/index'
import { Route as AuthedBukuIndexRouteImport } from './routes/_authed/buku/index'
import { Route as AuthedAnggotaIndexRouteImport } from './routes/_authed/anggota/index'
import { Route as AuthedSettingsMasterDataRouteImport } from './routes/_authed/settings/master-data'
import { Route as AuthedSettingsKtaRouteImport } from './routes/_authed/settings/kta'
import { Route as AuthedPeminjamanNewRouteImport } from './routes/_authed/peminjaman/new'
import { Route as AuthedPeminjamanIdRouteImport } from './routes/_authed/peminjaman/$id'
import { Route as AuthedLaporanTopPeminjamRouteImport } from './routes/_authed/laporan/top-peminjam'
import { Route as AuthedLaporanTopBukuRouteImport } from './routes/_authed/laporan/top-buku'
import { Route as AuthedLaporanKasRouteImport } from './routes/_authed/laporan/kas'
import { Route as AuthedLaporanGrafikRouteImport } from './routes/_authed/laporan/grafik'
import { Route as AuthedLaporanBackupRouteImport } from './routes/_authed/laporan/backup'
import { Route as AuthedBukuNewRouteImport } from './routes/_authed/buku/new'
import { Route as AuthedBukuIdRouteImport } from './routes/_authed/buku/$id'
import { Route as AuthedAnggotaNewRouteImport } from './routes/_authed/anggota/new'
import { Route as AuthedAnggotaCetakKtaRouteImport } from './routes/_authed/anggota/cetak-kta'
import { Route as AuthedAnggotaIdRouteImport } from './routes/_authed/anggota/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLaporanRoute = AuthedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedKunjunganRoute = AuthedKunjunganRouteImport.update({
  id: '/kunjungan',
  path: '/kunjungan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPengembalianIndexRoute = AuthedPengembalianIndexRouteImport.update({
  id: '/pengembalian/',
  path: '/pengembalian/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeminjamanIndexRoute = AuthedPeminjamanIndexRouteImport.update({
  id: '/peminjaman/',
  path: '/peminjaman/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLaporanIndexRoute = AuthedLaporanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedLaporanRoute,
} as any)
const AuthedBukuIndexRoute = AuthedBukuIndexRouteImport.update({
  id: '/buku/',
  path: '/buku/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnggotaIndexRoute = AuthedAnggotaIndexRouteImport.update({
  id: '/anggota/',
  path: '/anggota/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsMasterDataRoute =
  AuthedSettingsMasterDataRouteImport.update({
    id: '/settings/master-data',
    path: '/settings/master-data',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSettingsKtaRoute = AuthedSettingsKtaRouteImport.update({
  id: '/settings/kta',
  path: '/settings/kta',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeminjamanNewRoute = AuthedPeminjamanNewRouteImport.update({
  id: '/peminjaman/new',
  path: '/peminjaman/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeminjamanIdRoute = AuthedPeminjamanIdRouteImport.update({
  id: '/peminjaman/$id',
  path: '/peminjaman/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLaporanTopPeminjamRoute =
  AuthedLaporanTopPeminjamRouteImport.update({
    id: '/top-peminjam',
    path: '/top-peminjam',
    getParentRoute: () => AuthedLaporanRoute,
  } as any)
const AuthedLaporanTopBukuRoute = AuthedLaporanTopBukuRouteImport.update({
  id: '/top-buku',
  path: '/top-buku',
  getParentRoute: () => AuthedLaporanRoute,
} as any)
const AuthedLaporanKasRoute = AuthedLaporanKasRouteImport.update({
  id: '/kas',
  path: '/kas',
  getParentRoute: () => AuthedLaporanRoute,
} as any)
const AuthedLaporanGrafikRoute = AuthedLaporanGrafikRouteImport.update({
  id: '/grafik',
  path: '/grafik',
  getParentRoute: () => AuthedLaporanRoute,
} as any)
const AuthedLaporanBackupRoute = AuthedLaporanBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthedLaporanRoute,
} as any)
const AuthedBukuNewRoute = AuthedBukuNewRouteImport.update({
  id: '/buku/new',
  path: '/buku/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBukuIdRoute = AuthedBukuIdRouteImport.update({
  id: '/buku/$id',
  path: '/buku/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnggotaNewRoute = AuthedAnggotaNewRouteImport.update({
  id: '/anggota/new',
  path: '/anggota/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnggotaCetakKtaRoute = AuthedAnggotaCetakKtaRouteImport.update({
  id: '/anggota/cetak-kta',
  path: '/anggota/cetak-kta',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnggotaIdRoute = AuthedAnggotaIdRouteImport.update({
  id: '/anggota/$id',
  path: '/anggota/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/kunjungan': typeof AuthedKunjunganRoute
  '/laporan': typeof AuthedLaporanRouteWithChildren
  '/anggota/$id': typeof AuthedAnggotaIdRoute
  '/anggota/cetak-kta': typeof AuthedAnggotaCetakKtaRoute
  '/anggota/new': typeof AuthedAnggotaNewRoute
  '/buku/$id': typeof AuthedBukuIdRoute
  '/buku/new': typeof AuthedBukuNewRoute
  '/laporan/backup': typeof AuthedLaporanBackupRoute
  '/laporan/grafik': typeof AuthedLaporanGrafikRoute
  '/laporan/kas': typeof AuthedLaporanKasRoute
  '/laporan/top-buku': typeof AuthedLaporanTopBukuRoute
  '/laporan/top-peminjam': typeof AuthedLaporanTopPeminjamRoute
  '/peminjaman/$id': typeof AuthedPeminjamanIdRoute
  '/peminjaman/new': typeof AuthedPeminjamanNewRoute
  '/settings/kta': typeof AuthedSettingsKtaRoute
  '/settings/master-data': typeof AuthedSettingsMasterDataRoute
  '/anggota/': typeof AuthedAnggotaIndexRoute
  '/buku/': typeof AuthedBukuIndexRoute
  '/laporan/': typeof AuthedLaporanIndexRoute
  '/peminjaman/': typeof AuthedPeminjamanIndexRoute
  '/pengembalian/': typeof AuthedPengembalianIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/kunjungan': typeof AuthedKunjunganRoute
  '/anggota/$id': typeof AuthedAnggotaIdRoute
  '/anggota/cetak-kta': typeof AuthedAnggotaCetakKtaRoute
  '/anggota/new': typeof AuthedAnggotaNewRoute
  '/buku/$id': typeof AuthedBukuIdRoute
  '/buku/new': typeof AuthedBukuNewRoute
  '/laporan/backup': typeof AuthedLaporanBackupRoute
  '/laporan/grafik': typeof AuthedLaporanGrafikRoute
  '/laporan/kas': typeof AuthedLaporanKasRoute
  '/laporan/top-buku': typeof AuthedLaporanTopBukuRoute
  '/laporan/top-peminjam': typeof AuthedLaporanTopPeminjamRoute
  '/peminjaman/$id': typeof AuthedPeminjamanIdRoute
  '/peminjaman/new': typeof AuthedPeminjamanNewRoute
  '/settings/kta': typeof AuthedSettingsKtaRoute
  '/settings/master-data': typeof AuthedSettingsMasterDataRoute
  '/anggota': typeof AuthedAnggotaIndexRoute
  '/buku': typeof AuthedBukuIndexRoute
  '/laporan': typeof AuthedLaporanIndexRoute
  '/peminjaman': typeof AuthedPeminjamanIndexRoute
  '/pengembalian': typeof AuthedPengembalianIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/kunjungan': typeof AuthedKunjunganRoute
  '/_authed/laporan': typeof AuthedLaporanRouteWithChildren
  '/_authed/anggota/$id': typeof AuthedAnggotaIdRoute
  '/_authed/anggota/cetak-kta': typeof AuthedAnggotaCetakKtaRoute
  '/_authed/anggota/new': typeof AuthedAnggotaNewRoute
  '/_authed/buku/$id': typeof AuthedBukuIdRoute
  '/_authed/buku/new': typeof AuthedBukuNewRoute
  '/_authed/laporan/backup': typeof AuthedLaporanBackupRoute
  '/_authed/laporan/grafik': typeof AuthedLaporanGrafikRoute
  '/_authed/laporan/kas': typeof AuthedLaporanKasRoute
  '/_authed/laporan/top-buku': typeof AuthedLaporanTopBukuRoute
  '/_authed/laporan/top-peminjam': typeof AuthedLaporanTopPeminjamRoute
  '/_authed/peminjaman/$id': typeof AuthedPeminjamanIdRoute
  '/_authed/peminjaman/new': typeof AuthedPeminjamanNewRoute
  '/_authed/settings/kta': typeof AuthedSettingsKtaRoute
  '/_authed/settings/master-data': typeof AuthedSettingsMasterDataRoute
  '/_authed/anggota/': typeof AuthedAnggotaIndexRoute
  '/_authed/buku/': typeof AuthedBukuIndexRoute
  '/_authed/laporan/': typeof AuthedLaporanIndexRoute
  '/_authed/peminjaman/': typeof AuthedPeminjamanIndexRoute
  '/_authed/pengembalian/': typeof AuthedPengembalianIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/kunjungan'
    | '/laporan'
    | '/anggota/$id'
    | '/anggota/cetak-kta'
    | '/anggota/new'
    | '/buku/$id'
    | '/buku/new'
    | '/laporan/backup'
    | '/laporan/grafik'
    | '/laporan/kas'
    | '/laporan/top-buku'
    | '/laporan/top-peminjam'
    | '/peminjaman/$id'
    | '/peminjaman/new'
    | '/settings/kta'
    | '/settings/master-data'
    | '/anggota/'
    | '/buku/'
    | '/laporan/'
    | '/peminjaman/'
    | '/pengembalian/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/kunjungan'
    | '/anggota/$id'
    | '/anggota/cetak-kta'
    | '/anggota/new'
    | '/buku/$id'
    | '/buku/new'
    | '/laporan/backup'
    | '/laporan/grafik'
    | '/laporan/kas'
    | '/laporan/top-buku'
    | '/laporan/top-peminjam'
    | '/peminjaman/$id'
    | '/peminjaman/new'
    | '/settings/kta'
    | '/settings/master-data'
    | '/anggota'
    | '/buku'
    | '/laporan'
    | '/peminjaman'
    | '/pengembalian'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/kunjungan'
    | '/_authed/laporan'
    | '/_authed/anggota/$id'
    | '/_authed/anggota/cetak-kta'
    | '/_authed/anggota/new'
    | '/_authed/buku/$id'
    | '/_authed/buku/new'
    | '/_authed/laporan/backup'
    | '/_authed/laporan/grafik'
    | '/_authed/laporan/kas'
    | '/_authed/laporan/top-buku'
    | '/_authed/laporan/top-peminjam'
    | '/_authed/peminjaman/$id'
    | '/_authed/peminjaman/new'
    | '/_authed/settings/kta'
    | '/_authed/settings/master-data'
    | '/_authed/anggota/'
    | '/_authed/buku/'
    | '/_authed/laporan/'
    | '/_authed/peminjaman/'
    | '/_authed/pengembalian/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/laporan': {
      id: '/_authed/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthedLaporanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/kunjungan': {
      id: '/_authed/kunjungan'
      path: '/kunjungan'
      fullPath: '/kunjungan'
      preLoaderRoute: typeof AuthedKunjunganRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pengembalian/': {
      id: '/_authed/pengembalian/'
      path: '/pengembalian'
      fullPath: '/pengembalian/'
      preLoaderRoute: typeof AuthedPengembalianIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/peminjaman/': {
      id: '/_authed/peminjaman/'
      path: '/peminjaman'
      fullPath: '/peminjaman/'
      preLoaderRoute: typeof AuthedPeminjamanIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/laporan/': {
      id: '/_authed/laporan/'
      path: '/'
      fullPath: '/laporan/'
      preLoaderRoute: typeof AuthedLaporanIndexRouteImport
      parentRoute: typeof AuthedLaporanRoute
    }
    '/_authed/buku/': {
      id: '/_authed/buku/'
      path: '/buku'
      fullPath: '/buku/'
      preLoaderRoute: typeof AuthedBukuIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/anggota/': {
      id: '/_authed/anggota/'
      path: '/anggota'
      fullPath: '/anggota/'
      preLoaderRoute: typeof AuthedAnggotaIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/master-data': {
      id: '/_authed/settings/master-data'
      path: '/settings/master-data'
      fullPath: '/settings/master-data'
      preLoaderRoute: typeof AuthedSettingsMasterDataRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/kta': {
      id: '/_authed/settings/kta'
      path: '/settings/kta'
      fullPath: '/settings/kta'
      preLoaderRoute: typeof AuthedSettingsKtaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/peminjaman/new': {
      id: '/_authed/peminjaman/new'
      path: '/peminjaman/new'
      fullPath: '/peminjaman/new'
      preLoaderRoute: typeof AuthedPeminjamanNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/peminjaman/$id': {
      id: '/_authed/peminjaman/$id'
      path: '/peminjaman/$id'
      fullPath: '/peminjaman/$id'
      preLoaderRoute: typeof AuthedPeminjamanIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/laporan/top-peminjam': {
      id: '/_authed/laporan/top-peminjam'
      path: '/top-peminjam'
      fullPath: '/laporan/top-peminjam'
      preLoaderRoute: typeof AuthedLaporanTopPeminjamRouteImport
      parentRoute: typeof AuthedLaporanRoute
    }
    '/_authed/laporan/top-buku': {
      id: '/_authed/laporan/top-buku'
      path: '/top-buku'
      fullPath: '/laporan/top-buku'
      preLoaderRoute: typeof AuthedLaporanTopBukuRouteImport
      parentRoute: typeof AuthedLaporanRoute
    }
    '/_authed/laporan/kas': {
      id: '/_authed/laporan/kas'
      path: '/kas'
      fullPath: '/laporan/kas'
      preLoaderRoute: typeof AuthedLaporanKasRouteImport
      parentRoute: typeof AuthedLaporanRoute
    }
    '/_authed/laporan/grafik': {
      id: '/_authed/laporan/grafik'
      path: '/grafik'
      fullPath: '/laporan/grafik'
      preLoaderRoute: typeof AuthedLaporanGrafikRouteImport
      parentRoute: typeof AuthedLaporanRoute
    }
    '/_authed/laporan/backup': {
      id: '/_authed/laporan/backup'
      path: '/backup'
      fullPath: '/laporan/backup'
      preLoaderRoute: typeof AuthedLaporanBackupRouteImport
      parentRoute: typeof AuthedLaporanRoute
    }
    '/_authed/buku/new': {
      id: '/_authed/buku/new'
      path: '/buku/new'
      fullPath: '/buku/new'
      preLoaderRoute: typeof AuthedBukuNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/buku/$id': {
      id: '/_authed/buku/$id'
      path: '/buku/$id'
      fullPath: '/buku/$id'
      preLoaderRoute: typeof AuthedBukuIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/anggota/new': {
      id: '/_authed/anggota/new'
      path: '/anggota/new'
      fullPath: '/anggota/new'
      preLoaderRoute: typeof AuthedAnggotaNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/anggota/cetak-kta': {
      id: '/_authed/anggota/cetak-kta'
      path: '/anggota/cetak-kta'
      fullPath: '/anggota/cetak-kta'
      preLoaderRoute: typeof AuthedAnggotaCetakKtaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/anggota/$id': {
      id: '/_authed/anggota/$id'
      path: '/anggota/$id'
      fullPath: '/anggota/$id'
      preLoaderRoute: typeof AuthedAnggotaIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedLaporanRouteChildren {
  AuthedLaporanBackupRoute: typeof AuthedLaporanBackupRoute
  AuthedLaporanGrafikRoute: typeof AuthedLaporanGrafikRoute
  AuthedLaporanKasRoute: typeof AuthedLaporanKasRoute
  AuthedLaporanTopBukuRoute: typeof AuthedLaporanTopBukuRoute
  AuthedLaporanTopPeminjamRoute: typeof AuthedLaporanTopPeminjamRoute
  AuthedLaporanIndexRoute: typeof AuthedLaporanIndexRoute
}

const AuthedLaporanRouteChildren: AuthedLaporanRouteChildren = {
  AuthedLaporanBackupRoute: AuthedLaporanBackupRoute,
  AuthedLaporanGrafikRoute: AuthedLaporanGrafikRoute,
  AuthedLaporanKasRoute: AuthedLaporanKasRoute,
  AuthedLaporanTopBukuRoute: AuthedLaporanTopBukuRoute,
  AuthedLaporanTopPeminjamRoute: AuthedLaporanTopPeminjamRoute,
  AuthedLaporanIndexRoute: AuthedLaporanIndexRoute,
}

const AuthedLaporanRouteWithChildren = AuthedLaporanRoute._addFileChildren(
  AuthedLaporanRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedKunjunganRoute: typeof AuthedKunjunganRoute
  AuthedLaporanRoute: typeof AuthedLaporanRouteWithChildren
  AuthedAnggotaIdRoute: typeof AuthedAnggotaIdRoute
  AuthedAnggotaCetakKtaRoute: typeof AuthedAnggotaCetakKtaRoute
  AuthedAnggotaNewRoute: typeof AuthedAnggotaNewRoute
  AuthedBukuIdRoute: typeof AuthedBukuIdRoute
  AuthedBukuNewRoute: typeof AuthedBukuNewRoute
  AuthedPeminjamanIdRoute: typeof AuthedPeminjamanIdRoute
  AuthedPeminjamanNewRoute: typeof AuthedPeminjamanNewRoute
  AuthedSettingsKtaRoute: typeof AuthedSettingsKtaRoute
  AuthedSettingsMasterDataRoute: typeof AuthedSettingsMasterDataRoute
  AuthedAnggotaIndexRoute: typeof AuthedAnggotaIndexRoute
  AuthedBukuIndexRoute: typeof AuthedBukuIndexRoute
  AuthedPeminjamanIndexRoute: typeof AuthedPeminjamanIndexRoute
  AuthedPengembalianIndexRoute: typeof AuthedPengembalianIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedKunjunganRoute: AuthedKunjunganRoute,
  AuthedLaporanRoute: AuthedLaporanRouteWithChildren,
  AuthedAnggotaIdRoute: AuthedAnggotaIdRoute,
  AuthedAnggotaCetakKtaRoute: AuthedAnggotaCetakKtaRoute,
  AuthedAnggotaNewRoute: AuthedAnggotaNewRoute,
  AuthedBukuIdRoute: AuthedBukuIdRoute,
  AuthedBukuNewRoute: AuthedBukuNewRoute,
  AuthedPeminjamanIdRoute: AuthedPeminjamanIdRoute,
  AuthedPeminjamanNewRoute: AuthedPeminjamanNewRoute,
  AuthedSettingsKtaRoute: AuthedSettingsKtaRoute,
  AuthedSettingsMasterDataRoute: AuthedSettingsMasterDataRoute,
  AuthedAnggotaIndexRoute: AuthedAnggotaIndexRoute,
  AuthedBukuIndexRoute: AuthedBukuIndexRoute,
  AuthedPeminjamanIndexRoute: AuthedPeminjamanIndexRoute,
  AuthedPengembalianIndexRoute: AuthedPengembalianIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
