/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedBukuIndexRouteImport } from './routes/_authed/buku/index'
import { Route as AuthedAnggotaIndexRouteImport } from './routes/_authed/anggota/index'
import { Route as AuthedSettingsMasterDataRouteImport } from './routes/_authed/settings/master-data'
import { Route as AuthedBukuNewRouteImport } from './routes/_authed/buku/new'
import { Route as AuthedBukuIdRouteImport } from './routes/_authed/buku/$id'
import { Route as AuthedAnggotaNewRouteImport } from './routes/_authed/anggota/new'
import { Route as AuthedAnggotaIdRouteImport } from './routes/_authed/anggota/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBukuIndexRoute = AuthedBukuIndexRouteImport.update({
  id: '/buku/',
  path: '/buku/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnggotaIndexRoute = AuthedAnggotaIndexRouteImport.update({
  id: '/anggota/',
  path: '/anggota/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsMasterDataRoute =
  AuthedSettingsMasterDataRouteImport.update({
    id: '/settings/master-data',
    path: '/settings/master-data',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedBukuNewRoute = AuthedBukuNewRouteImport.update({
  id: '/buku/new',
  path: '/buku/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBukuIdRoute = AuthedBukuIdRouteImport.update({
  id: '/buku/$id',
  path: '/buku/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnggotaNewRoute = AuthedAnggotaNewRouteImport.update({
  id: '/anggota/new',
  path: '/anggota/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnggotaIdRoute = AuthedAnggotaIdRouteImport.update({
  id: '/anggota/$id',
  path: '/anggota/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/anggota/$id': typeof AuthedAnggotaIdRoute
  '/anggota/new': typeof AuthedAnggotaNewRoute
  '/buku/$id': typeof AuthedBukuIdRoute
  '/buku/new': typeof AuthedBukuNewRoute
  '/settings/master-data': typeof AuthedSettingsMasterDataRoute
  '/anggota/': typeof AuthedAnggotaIndexRoute
  '/buku/': typeof AuthedBukuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/anggota/$id': typeof AuthedAnggotaIdRoute
  '/anggota/new': typeof AuthedAnggotaNewRoute
  '/buku/$id': typeof AuthedBukuIdRoute
  '/buku/new': typeof AuthedBukuNewRoute
  '/settings/master-data': typeof AuthedSettingsMasterDataRoute
  '/anggota': typeof AuthedAnggotaIndexRoute
  '/buku': typeof AuthedBukuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/anggota/$id': typeof AuthedAnggotaIdRoute
  '/_authed/anggota/new': typeof AuthedAnggotaNewRoute
  '/_authed/buku/$id': typeof AuthedBukuIdRoute
  '/_authed/buku/new': typeof AuthedBukuNewRoute
  '/_authed/settings/master-data': typeof AuthedSettingsMasterDataRoute
  '/_authed/anggota/': typeof AuthedAnggotaIndexRoute
  '/_authed/buku/': typeof AuthedBukuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/anggota/$id'
    | '/anggota/new'
    | '/buku/$id'
    | '/buku/new'
    | '/settings/master-data'
    | '/anggota/'
    | '/buku/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/anggota/$id'
    | '/anggota/new'
    | '/buku/$id'
    | '/buku/new'
    | '/settings/master-data'
    | '/anggota'
    | '/buku'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/anggota/$id'
    | '/_authed/anggota/new'
    | '/_authed/buku/$id'
    | '/_authed/buku/new'
    | '/_authed/settings/master-data'
    | '/_authed/anggota/'
    | '/_authed/buku/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/buku/': {
      id: '/_authed/buku/'
      path: '/buku'
      fullPath: '/buku/'
      preLoaderRoute: typeof AuthedBukuIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/anggota/': {
      id: '/_authed/anggota/'
      path: '/anggota'
      fullPath: '/anggota/'
      preLoaderRoute: typeof AuthedAnggotaIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/master-data': {
      id: '/_authed/settings/master-data'
      path: '/settings/master-data'
      fullPath: '/settings/master-data'
      preLoaderRoute: typeof AuthedSettingsMasterDataRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/buku/new': {
      id: '/_authed/buku/new'
      path: '/buku/new'
      fullPath: '/buku/new'
      preLoaderRoute: typeof AuthedBukuNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/buku/$id': {
      id: '/_authed/buku/$id'
      path: '/buku/$id'
      fullPath: '/buku/$id'
      preLoaderRoute: typeof AuthedBukuIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/anggota/new': {
      id: '/_authed/anggota/new'
      path: '/anggota/new'
      fullPath: '/anggota/new'
      preLoaderRoute: typeof AuthedAnggotaNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/anggota/$id': {
      id: '/_authed/anggota/$id'
      path: '/anggota/$id'
      fullPath: '/anggota/$id'
      preLoaderRoute: typeof AuthedAnggotaIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedAnggotaIdRoute: typeof AuthedAnggotaIdRoute
  AuthedAnggotaNewRoute: typeof AuthedAnggotaNewRoute
  AuthedBukuIdRoute: typeof AuthedBukuIdRoute
  AuthedBukuNewRoute: typeof AuthedBukuNewRoute
  AuthedSettingsMasterDataRoute: typeof AuthedSettingsMasterDataRoute
  AuthedAnggotaIndexRoute: typeof AuthedAnggotaIndexRoute
  AuthedBukuIndexRoute: typeof AuthedBukuIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedAnggotaIdRoute: AuthedAnggotaIdRoute,
  AuthedAnggotaNewRoute: AuthedAnggotaNewRoute,
  AuthedBukuIdRoute: AuthedBukuIdRoute,
  AuthedBukuNewRoute: AuthedBukuNewRoute,
  AuthedSettingsMasterDataRoute: AuthedSettingsMasterDataRoute,
  AuthedAnggotaIndexRoute: AuthedAnggotaIndexRoute,
  AuthedBukuIndexRoute: AuthedBukuIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
