/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedLaporanRouteImport } from './routes/_authed/laporan'
import { Route as AuthedKunjunganRouteImport } from './routes/_authed/kunjungan'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedPengembalianIndexRouteImport } from './routes/_authed/pengembalian/index'
import { Route as AuthedPeminjamanIndexRouteImport } from './routes/_authed/peminjaman/index'
import { Route as AuthedLaporanIndexRouteImport } from './routes/_authed/laporan/index'
import { Route as AuthedBukuIndexRouteImport } from './routes/_authed/buku/index'
import { Route as AuthedAnggotaIndexRouteImport } from './routes/_authed/anggota/index'
import { Route as AuthedSettingsTentangRouteImport } from './routes/_authed/settings/tentang'
import { Route as AuthedSettingsTampilanRouteImport } from './routes/_authed/settings/tampilan'
import { Route as AuthedSettingsSinkronisasiRouteImport } from './routes/_authed/settings/sinkronisasi'
import { Route as AuthedSettingsMasterDataRouteImport } from './routes/_authed/settings/master-data'
import { Route as AuthedSettingsManualRouteImport } from './routes/_authed/settings/manual'
import { Route as AuthedSettingsKtaRouteImport } from './routes/_authed/settings/kta'
import { Route as AuthedSettingsIdentitasRouteImport } from './routes/_authed/settings/identitas'
import { Route as AuthedSettingsHakAksesRouteImport } from './routes/_authed/settings/hak-akses'
import { Route as AuthedSettingsBahasaRouteImport } from './routes/_authed/settings/bahasa'
import { Route as AuthedSettingsBackupRouteImport } from './routes/_authed/settings/backup'
import { Route as AuthedSettingsAuditLogRouteImport } from './routes/_authed/settings/audit-log'
import { Route as AuthedSettingsAturanPeminjamanRouteImport } from './routes/_authed/settings/aturan-peminjaman'
import { Route as AuthedSettingsAkunRouteImport } from './routes/_authed/settings/akun'
import { Route as AuthedPeminjamanNewRouteImport } from './routes/_authed/peminjaman/new'
import { Route as AuthedPeminjamanIdRouteImport } from './routes/_authed/peminjaman/$id'
import { Route as AuthedLaporanTopPeminjamRouteImport } from './routes/_authed/laporan/top-peminjam'
import { Route as AuthedLaporanTopBukuRouteImport } from './routes/_authed/laporan/top-buku'
import { Route as AuthedLaporanKasRouteImport } from './routes/_authed/laporan/kas'
import { Route as AuthedLaporanGrafikRouteImport } from './routes/_authed/laporan/grafik'
import { Route as AuthedLaporanBackupRouteImport } from './routes/_authed/laporan/backup'
import { Route as AuthedBukuNewRouteImport } from './routes/_authed/buku/new'
import { Route as AuthedBukuIdRouteImport } from './routes/_authed/buku/$id'
import { Route as AuthedAnggotaNewRouteImport } from './routes/_authed/anggota/new'
import { Route as AuthedAnggotaCetakKtaRouteImport } from './routes/_authed/anggota/cetak-kta'
import { Route as AuthedAnggotaIdRouteImport } from './routes/_authed/anggota/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLaporanRoute = AuthedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedKunjunganRoute = AuthedKunjunganRouteImport.update({
  id: '/kunjungan',
  path: '/kunjungan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedPengembalianIndexRoute = AuthedPengembalianIndexRouteImport.update({
  id: '/pengembalian/',
  path: '/pengembalian/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeminjamanIndexRoute = AuthedPeminjamanIndexRouteImport.update({
  id: '/peminjaman/',
  path: '/peminjaman/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLaporanIndexRoute = AuthedLaporanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedLaporanRoute,
} as any)
const AuthedBukuIndexRoute = AuthedBukuIndexRouteImport.update({
  id: '/buku/',
  path: '/buku/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnggotaIndexRoute = AuthedAnggotaIndexRouteImport.update({
  id: '/anggota/',
  path: '/anggota/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsTentangRoute = AuthedSettingsTentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsTampilanRoute = AuthedSettingsTampilanRouteImport.update({
  id: '/tampilan',
  path: '/tampilan',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsSinkronisasiRoute =
  AuthedSettingsSinkronisasiRouteImport.update({
    id: '/sinkronisasi',
    path: '/sinkronisasi',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsMasterDataRoute =
  AuthedSettingsMasterDataRouteImport.update({
    id: '/master-data',
    path: '/master-data',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsManualRoute = AuthedSettingsManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsKtaRoute = AuthedSettingsKtaRouteImport.update({
  id: '/kta',
  path: '/kta',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsIdentitasRoute = AuthedSettingsIdentitasRouteImport.update({
  id: '/identitas',
  path: '/identitas',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsHakAksesRoute = AuthedSettingsHakAksesRouteImport.update({
  id: '/hak-akses',
  path: '/hak-akses',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsBahasaRoute = AuthedSettingsBahasaRouteImport.update({
  id: '/bahasa',
  path: '/bahasa',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsBackupRoute = AuthedSettingsBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsAuditLogRoute = AuthedSettingsAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsAturanPeminjamanRoute =
  AuthedSettingsAturanPeminjamanRouteImport.update({
    id: '/aturan-peminjaman',
    path: '/aturan-peminjaman',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsAkunRoute = AuthedSettingsAkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedPeminjamanNewRoute = AuthedPeminjamanNewRouteImport.update({
  id: '/peminjaman/new',
  path: '/peminjaman/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeminjamanIdRoute = AuthedPeminjamanIdRouteImport.update({
  id: '/peminjaman/$id',
  path: '/peminjaman/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLaporanTopPeminjamRoute =
  AuthedLaporanTopPeminjamRouteImport.update({
    id: '/top-peminjam',
    path: '/top-peminjam',
    getParentRoute: () => AuthedLaporanRoute,
  } as any)
const AuthedLaporanTopBukuRoute = AuthedLaporanTopBukuRouteImport.update({
  id: '/top-buku',
  path: '/top-buku',
  getParentRoute: () => AuthedLaporanRoute,
} as any)
const AuthedLaporanKasRoute = AuthedLaporanKasRouteImport.update({
  id: '/kas',
  path: '/kas',
  getParentRoute: () => AuthedLaporanRoute,
} as any)
const AuthedLaporanGrafikRoute = AuthedLaporanGrafikRouteImport.update({
  id: '/grafik',
  path: '/grafik',
  getParentRoute: () => AuthedLaporanRoute,
} as any)
const AuthedLaporanBackupRoute = AuthedLaporanBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthedLaporanRoute,
} as any)
const AuthedBukuNewRoute = AuthedBukuNewRouteImport.update({
  id: '/buku/new',
  path: '/buku/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBukuIdRoute = AuthedBukuIdRouteImport.update({
  id: '/buku/$id',
  path: '/buku/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnggotaNewRoute = AuthedAnggotaNewRouteImport.update({
  id: '/anggota/new',
  path: '/anggota/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnggotaCetakKtaRoute = AuthedAnggotaCetakKtaRouteImport.update({
  id: '/anggota/cetak-kta',
  path: '/anggota/cetak-kta',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnggotaIdRoute = AuthedAnggotaIdRouteImport.update({
  id: '/anggota/$id',
  path: '/anggota/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/kunjungan': typeof AuthedKunjunganRoute
  '/laporan': typeof AuthedLaporanRouteWithChildren
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/anggota/$id': typeof AuthedAnggotaIdRoute
  '/anggota/cetak-kta': typeof AuthedAnggotaCetakKtaRoute
  '/anggota/new': typeof AuthedAnggotaNewRoute
  '/buku/$id': typeof AuthedBukuIdRoute
  '/buku/new': typeof AuthedBukuNewRoute
  '/laporan/backup': typeof AuthedLaporanBackupRoute
  '/laporan/grafik': typeof AuthedLaporanGrafikRoute
  '/laporan/kas': typeof AuthedLaporanKasRoute
  '/laporan/top-buku': typeof AuthedLaporanTopBukuRoute
  '/laporan/top-peminjam': typeof AuthedLaporanTopPeminjamRoute
  '/peminjaman/$id': typeof AuthedPeminjamanIdRoute
  '/peminjaman/new': typeof AuthedPeminjamanNewRoute
  '/settings/akun': typeof AuthedSettingsAkunRoute
  '/settings/aturan-peminjaman': typeof AuthedSettingsAturanPeminjamanRoute
  '/settings/audit-log': typeof AuthedSettingsAuditLogRoute
  '/settings/backup': typeof AuthedSettingsBackupRoute
  '/settings/bahasa': typeof AuthedSettingsBahasaRoute
  '/settings/hak-akses': typeof AuthedSettingsHakAksesRoute
  '/settings/identitas': typeof AuthedSettingsIdentitasRoute
  '/settings/kta': typeof AuthedSettingsKtaRoute
  '/settings/manual': typeof AuthedSettingsManualRoute
  '/settings/master-data': typeof AuthedSettingsMasterDataRoute
  '/settings/sinkronisasi': typeof AuthedSettingsSinkronisasiRoute
  '/settings/tampilan': typeof AuthedSettingsTampilanRoute
  '/settings/tentang': typeof AuthedSettingsTentangRoute
  '/anggota/': typeof AuthedAnggotaIndexRoute
  '/buku/': typeof AuthedBukuIndexRoute
  '/laporan/': typeof AuthedLaporanIndexRoute
  '/peminjaman/': typeof AuthedPeminjamanIndexRoute
  '/pengembalian/': typeof AuthedPengembalianIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/kunjungan': typeof AuthedKunjunganRoute
  '/anggota/$id': typeof AuthedAnggotaIdRoute
  '/anggota/cetak-kta': typeof AuthedAnggotaCetakKtaRoute
  '/anggota/new': typeof AuthedAnggotaNewRoute
  '/buku/$id': typeof AuthedBukuIdRoute
  '/buku/new': typeof AuthedBukuNewRoute
  '/laporan/backup': typeof AuthedLaporanBackupRoute
  '/laporan/grafik': typeof AuthedLaporanGrafikRoute
  '/laporan/kas': typeof AuthedLaporanKasRoute
  '/laporan/top-buku': typeof AuthedLaporanTopBukuRoute
  '/laporan/top-peminjam': typeof AuthedLaporanTopPeminjamRoute
  '/peminjaman/$id': typeof AuthedPeminjamanIdRoute
  '/peminjaman/new': typeof AuthedPeminjamanNewRoute
  '/settings/akun': typeof AuthedSettingsAkunRoute
  '/settings/aturan-peminjaman': typeof AuthedSettingsAturanPeminjamanRoute
  '/settings/audit-log': typeof AuthedSettingsAuditLogRoute
  '/settings/backup': typeof AuthedSettingsBackupRoute
  '/settings/bahasa': typeof AuthedSettingsBahasaRoute
  '/settings/hak-akses': typeof AuthedSettingsHakAksesRoute
  '/settings/identitas': typeof AuthedSettingsIdentitasRoute
  '/settings/kta': typeof AuthedSettingsKtaRoute
  '/settings/manual': typeof AuthedSettingsManualRoute
  '/settings/master-data': typeof AuthedSettingsMasterDataRoute
  '/settings/sinkronisasi': typeof AuthedSettingsSinkronisasiRoute
  '/settings/tampilan': typeof AuthedSettingsTampilanRoute
  '/settings/tentang': typeof AuthedSettingsTentangRoute
  '/anggota': typeof AuthedAnggotaIndexRoute
  '/buku': typeof AuthedBukuIndexRoute
  '/laporan': typeof AuthedLaporanIndexRoute
  '/peminjaman': typeof AuthedPeminjamanIndexRoute
  '/pengembalian': typeof AuthedPengembalianIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/kunjungan': typeof AuthedKunjunganRoute
  '/_authed/laporan': typeof AuthedLaporanRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/_authed/anggota/$id': typeof AuthedAnggotaIdRoute
  '/_authed/anggota/cetak-kta': typeof AuthedAnggotaCetakKtaRoute
  '/_authed/anggota/new': typeof AuthedAnggotaNewRoute
  '/_authed/buku/$id': typeof AuthedBukuIdRoute
  '/_authed/buku/new': typeof AuthedBukuNewRoute
  '/_authed/laporan/backup': typeof AuthedLaporanBackupRoute
  '/_authed/laporan/grafik': typeof AuthedLaporanGrafikRoute
  '/_authed/laporan/kas': typeof AuthedLaporanKasRoute
  '/_authed/laporan/top-buku': typeof AuthedLaporanTopBukuRoute
  '/_authed/laporan/top-peminjam': typeof AuthedLaporanTopPeminjamRoute
  '/_authed/peminjaman/$id': typeof AuthedPeminjamanIdRoute
  '/_authed/peminjaman/new': typeof AuthedPeminjamanNewRoute
  '/_authed/settings/akun': typeof AuthedSettingsAkunRoute
  '/_authed/settings/aturan-peminjaman': typeof AuthedSettingsAturanPeminjamanRoute
  '/_authed/settings/audit-log': typeof AuthedSettingsAuditLogRoute
  '/_authed/settings/backup': typeof AuthedSettingsBackupRoute
  '/_authed/settings/bahasa': typeof AuthedSettingsBahasaRoute
  '/_authed/settings/hak-akses': typeof AuthedSettingsHakAksesRoute
  '/_authed/settings/identitas': typeof AuthedSettingsIdentitasRoute
  '/_authed/settings/kta': typeof AuthedSettingsKtaRoute
  '/_authed/settings/manual': typeof AuthedSettingsManualRoute
  '/_authed/settings/master-data': typeof AuthedSettingsMasterDataRoute
  '/_authed/settings/sinkronisasi': typeof AuthedSettingsSinkronisasiRoute
  '/_authed/settings/tampilan': typeof AuthedSettingsTampilanRoute
  '/_authed/settings/tentang': typeof AuthedSettingsTentangRoute
  '/_authed/anggota/': typeof AuthedAnggotaIndexRoute
  '/_authed/buku/': typeof AuthedBukuIndexRoute
  '/_authed/laporan/': typeof AuthedLaporanIndexRoute
  '/_authed/peminjaman/': typeof AuthedPeminjamanIndexRoute
  '/_authed/pengembalian/': typeof AuthedPengembalianIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/kunjungan'
    | '/laporan'
    | '/settings'
    | '/anggota/$id'
    | '/anggota/cetak-kta'
    | '/anggota/new'
    | '/buku/$id'
    | '/buku/new'
    | '/laporan/backup'
    | '/laporan/grafik'
    | '/laporan/kas'
    | '/laporan/top-buku'
    | '/laporan/top-peminjam'
    | '/peminjaman/$id'
    | '/peminjaman/new'
    | '/settings/akun'
    | '/settings/aturan-peminjaman'
    | '/settings/audit-log'
    | '/settings/backup'
    | '/settings/bahasa'
    | '/settings/hak-akses'
    | '/settings/identitas'
    | '/settings/kta'
    | '/settings/manual'
    | '/settings/master-data'
    | '/settings/sinkronisasi'
    | '/settings/tampilan'
    | '/settings/tentang'
    | '/anggota/'
    | '/buku/'
    | '/laporan/'
    | '/peminjaman/'
    | '/pengembalian/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/kunjungan'
    | '/anggota/$id'
    | '/anggota/cetak-kta'
    | '/anggota/new'
    | '/buku/$id'
    | '/buku/new'
    | '/laporan/backup'
    | '/laporan/grafik'
    | '/laporan/kas'
    | '/laporan/top-buku'
    | '/laporan/top-peminjam'
    | '/peminjaman/$id'
    | '/peminjaman/new'
    | '/settings/akun'
    | '/settings/aturan-peminjaman'
    | '/settings/audit-log'
    | '/settings/backup'
    | '/settings/bahasa'
    | '/settings/hak-akses'
    | '/settings/identitas'
    | '/settings/kta'
    | '/settings/manual'
    | '/settings/master-data'
    | '/settings/sinkronisasi'
    | '/settings/tampilan'
    | '/settings/tentang'
    | '/anggota'
    | '/buku'
    | '/laporan'
    | '/peminjaman'
    | '/pengembalian'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/kunjungan'
    | '/_authed/laporan'
    | '/_authed/settings'
    | '/_authed/anggota/$id'
    | '/_authed/anggota/cetak-kta'
    | '/_authed/anggota/new'
    | '/_authed/buku/$id'
    | '/_authed/buku/new'
    | '/_authed/laporan/backup'
    | '/_authed/laporan/grafik'
    | '/_authed/laporan/kas'
    | '/_authed/laporan/top-buku'
    | '/_authed/laporan/top-peminjam'
    | '/_authed/peminjaman/$id'
    | '/_authed/peminjaman/new'
    | '/_authed/settings/akun'
    | '/_authed/settings/aturan-peminjaman'
    | '/_authed/settings/audit-log'
    | '/_authed/settings/backup'
    | '/_authed/settings/bahasa'
    | '/_authed/settings/hak-akses'
    | '/_authed/settings/identitas'
    | '/_authed/settings/kta'
    | '/_authed/settings/manual'
    | '/_authed/settings/master-data'
    | '/_authed/settings/sinkronisasi'
    | '/_authed/settings/tampilan'
    | '/_authed/settings/tentang'
    | '/_authed/anggota/'
    | '/_authed/buku/'
    | '/_authed/laporan/'
    | '/_authed/peminjaman/'
    | '/_authed/pengembalian/'
    | '/_authed/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/laporan': {
      id: '/_authed/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthedLaporanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/kunjungan': {
      id: '/_authed/kunjungan'
      path: '/kunjungan'
      fullPath: '/kunjungan'
      preLoaderRoute: typeof AuthedKunjunganRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/pengembalian/': {
      id: '/_authed/pengembalian/'
      path: '/pengembalian'
      fullPath: '/pengembalian/'
      preLoaderRoute: typeof AuthedPengembalianIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/peminjaman/': {
      id: '/_authed/peminjaman/'
      path: '/peminjaman'
      fullPath: '/peminjaman/'
      preLoaderRoute: typeof AuthedPeminjamanIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/laporan/': {
      id: '/_authed/laporan/'
      path: '/'
      fullPath: '/laporan/'
      preLoaderRoute: typeof AuthedLaporanIndexRouteImport
      parentRoute: typeof AuthedLaporanRoute
    }
    '/_authed/buku/': {
      id: '/_authed/buku/'
      path: '/buku'
      fullPath: '/buku/'
      preLoaderRoute: typeof AuthedBukuIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/anggota/': {
      id: '/_authed/anggota/'
      path: '/anggota'
      fullPath: '/anggota/'
      preLoaderRoute: typeof AuthedAnggotaIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/tentang': {
      id: '/_authed/settings/tentang'
      path: '/tentang'
      fullPath: '/settings/tentang'
      preLoaderRoute: typeof AuthedSettingsTentangRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/tampilan': {
      id: '/_authed/settings/tampilan'
      path: '/tampilan'
      fullPath: '/settings/tampilan'
      preLoaderRoute: typeof AuthedSettingsTampilanRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/sinkronisasi': {
      id: '/_authed/settings/sinkronisasi'
      path: '/sinkronisasi'
      fullPath: '/settings/sinkronisasi'
      preLoaderRoute: typeof AuthedSettingsSinkronisasiRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/master-data': {
      id: '/_authed/settings/master-data'
      path: '/master-data'
      fullPath: '/settings/master-data'
      preLoaderRoute: typeof AuthedSettingsMasterDataRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/manual': {
      id: '/_authed/settings/manual'
      path: '/manual'
      fullPath: '/settings/manual'
      preLoaderRoute: typeof AuthedSettingsManualRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/kta': {
      id: '/_authed/settings/kta'
      path: '/kta'
      fullPath: '/settings/kta'
      preLoaderRoute: typeof AuthedSettingsKtaRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/identitas': {
      id: '/_authed/settings/identitas'
      path: '/identitas'
      fullPath: '/settings/identitas'
      preLoaderRoute: typeof AuthedSettingsIdentitasRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/hak-akses': {
      id: '/_authed/settings/hak-akses'
      path: '/hak-akses'
      fullPath: '/settings/hak-akses'
      preLoaderRoute: typeof AuthedSettingsHakAksesRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/bahasa': {
      id: '/_authed/settings/bahasa'
      path: '/bahasa'
      fullPath: '/settings/bahasa'
      preLoaderRoute: typeof AuthedSettingsBahasaRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/backup': {
      id: '/_authed/settings/backup'
      path: '/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof AuthedSettingsBackupRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/audit-log': {
      id: '/_authed/settings/audit-log'
      path: '/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof AuthedSettingsAuditLogRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/aturan-peminjaman': {
      id: '/_authed/settings/aturan-peminjaman'
      path: '/aturan-peminjaman'
      fullPath: '/settings/aturan-peminjaman'
      preLoaderRoute: typeof AuthedSettingsAturanPeminjamanRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/akun': {
      id: '/_authed/settings/akun'
      path: '/akun'
      fullPath: '/settings/akun'
      preLoaderRoute: typeof AuthedSettingsAkunRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/peminjaman/new': {
      id: '/_authed/peminjaman/new'
      path: '/peminjaman/new'
      fullPath: '/peminjaman/new'
      preLoaderRoute: typeof AuthedPeminjamanNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/peminjaman/$id': {
      id: '/_authed/peminjaman/$id'
      path: '/peminjaman/$id'
      fullPath: '/peminjaman/$id'
      preLoaderRoute: typeof AuthedPeminjamanIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/laporan/top-peminjam': {
      id: '/_authed/laporan/top-peminjam'
      path: '/top-peminjam'
      fullPath: '/laporan/top-peminjam'
      preLoaderRoute: typeof AuthedLaporanTopPeminjamRouteImport
      parentRoute: typeof AuthedLaporanRoute
    }
    '/_authed/laporan/top-buku': {
      id: '/_authed/laporan/top-buku'
      path: '/top-buku'
      fullPath: '/laporan/top-buku'
      preLoaderRoute: typeof AuthedLaporanTopBukuRouteImport
      parentRoute: typeof AuthedLaporanRoute
    }
    '/_authed/laporan/kas': {
      id: '/_authed/laporan/kas'
      path: '/kas'
      fullPath: '/laporan/kas'
      preLoaderRoute: typeof AuthedLaporanKasRouteImport
      parentRoute: typeof AuthedLaporanRoute
    }
    '/_authed/laporan/grafik': {
      id: '/_authed/laporan/grafik'
      path: '/grafik'
      fullPath: '/laporan/grafik'
      preLoaderRoute: typeof AuthedLaporanGrafikRouteImport
      parentRoute: typeof AuthedLaporanRoute
    }
    '/_authed/laporan/backup': {
      id: '/_authed/laporan/backup'
      path: '/backup'
      fullPath: '/laporan/backup'
      preLoaderRoute: typeof AuthedLaporanBackupRouteImport
      parentRoute: typeof AuthedLaporanRoute
    }
    '/_authed/buku/new': {
      id: '/_authed/buku/new'
      path: '/buku/new'
      fullPath: '/buku/new'
      preLoaderRoute: typeof AuthedBukuNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/buku/$id': {
      id: '/_authed/buku/$id'
      path: '/buku/$id'
      fullPath: '/buku/$id'
      preLoaderRoute: typeof AuthedBukuIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/anggota/new': {
      id: '/_authed/anggota/new'
      path: '/anggota/new'
      fullPath: '/anggota/new'
      preLoaderRoute: typeof AuthedAnggotaNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/anggota/cetak-kta': {
      id: '/_authed/anggota/cetak-kta'
      path: '/anggota/cetak-kta'
      fullPath: '/anggota/cetak-kta'
      preLoaderRoute: typeof AuthedAnggotaCetakKtaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/anggota/$id': {
      id: '/_authed/anggota/$id'
      path: '/anggota/$id'
      fullPath: '/anggota/$id'
      preLoaderRoute: typeof AuthedAnggotaIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedLaporanRouteChildren {
  AuthedLaporanBackupRoute: typeof AuthedLaporanBackupRoute
  AuthedLaporanGrafikRoute: typeof AuthedLaporanGrafikRoute
  AuthedLaporanKasRoute: typeof AuthedLaporanKasRoute
  AuthedLaporanTopBukuRoute: typeof AuthedLaporanTopBukuRoute
  AuthedLaporanTopPeminjamRoute: typeof AuthedLaporanTopPeminjamRoute
  AuthedLaporanIndexRoute: typeof AuthedLaporanIndexRoute
}

const AuthedLaporanRouteChildren: AuthedLaporanRouteChildren = {
  AuthedLaporanBackupRoute: AuthedLaporanBackupRoute,
  AuthedLaporanGrafikRoute: AuthedLaporanGrafikRoute,
  AuthedLaporanKasRoute: AuthedLaporanKasRoute,
  AuthedLaporanTopBukuRoute: AuthedLaporanTopBukuRoute,
  AuthedLaporanTopPeminjamRoute: AuthedLaporanTopPeminjamRoute,
  AuthedLaporanIndexRoute: AuthedLaporanIndexRoute,
}

const AuthedLaporanRouteWithChildren = AuthedLaporanRoute._addFileChildren(
  AuthedLaporanRouteChildren,
)

interface AuthedSettingsRouteChildren {
  AuthedSettingsAkunRoute: typeof AuthedSettingsAkunRoute
  AuthedSettingsAturanPeminjamanRoute: typeof AuthedSettingsAturanPeminjamanRoute
  AuthedSettingsAuditLogRoute: typeof AuthedSettingsAuditLogRoute
  AuthedSettingsBackupRoute: typeof AuthedSettingsBackupRoute
  AuthedSettingsBahasaRoute: typeof AuthedSettingsBahasaRoute
  AuthedSettingsHakAksesRoute: typeof AuthedSettingsHakAksesRoute
  AuthedSettingsIdentitasRoute: typeof AuthedSettingsIdentitasRoute
  AuthedSettingsKtaRoute: typeof AuthedSettingsKtaRoute
  AuthedSettingsManualRoute: typeof AuthedSettingsManualRoute
  AuthedSettingsMasterDataRoute: typeof AuthedSettingsMasterDataRoute
  AuthedSettingsSinkronisasiRoute: typeof AuthedSettingsSinkronisasiRoute
  AuthedSettingsTampilanRoute: typeof AuthedSettingsTampilanRoute
  AuthedSettingsTentangRoute: typeof AuthedSettingsTentangRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsAkunRoute: AuthedSettingsAkunRoute,
  AuthedSettingsAturanPeminjamanRoute: AuthedSettingsAturanPeminjamanRoute,
  AuthedSettingsAuditLogRoute: AuthedSettingsAuditLogRoute,
  AuthedSettingsBackupRoute: AuthedSettingsBackupRoute,
  AuthedSettingsBahasaRoute: AuthedSettingsBahasaRoute,
  AuthedSettingsHakAksesRoute: AuthedSettingsHakAksesRoute,
  AuthedSettingsIdentitasRoute: AuthedSettingsIdentitasRoute,
  AuthedSettingsKtaRoute: AuthedSettingsKtaRoute,
  AuthedSettingsManualRoute: AuthedSettingsManualRoute,
  AuthedSettingsMasterDataRoute: AuthedSettingsMasterDataRoute,
  AuthedSettingsSinkronisasiRoute: AuthedSettingsSinkronisasiRoute,
  AuthedSettingsTampilanRoute: AuthedSettingsTampilanRoute,
  AuthedSettingsTentangRoute: AuthedSettingsTentangRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedKunjunganRoute: typeof AuthedKunjunganRoute
  AuthedLaporanRoute: typeof AuthedLaporanRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedAnggotaIdRoute: typeof AuthedAnggotaIdRoute
  AuthedAnggotaCetakKtaRoute: typeof AuthedAnggotaCetakKtaRoute
  AuthedAnggotaNewRoute: typeof AuthedAnggotaNewRoute
  AuthedBukuIdRoute: typeof AuthedBukuIdRoute
  AuthedBukuNewRoute: typeof AuthedBukuNewRoute
  AuthedPeminjamanIdRoute: typeof AuthedPeminjamanIdRoute
  AuthedPeminjamanNewRoute: typeof AuthedPeminjamanNewRoute
  AuthedAnggotaIndexRoute: typeof AuthedAnggotaIndexRoute
  AuthedBukuIndexRoute: typeof AuthedBukuIndexRoute
  AuthedPeminjamanIndexRoute: typeof AuthedPeminjamanIndexRoute
  AuthedPengembalianIndexRoute: typeof AuthedPengembalianIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedKunjunganRoute: AuthedKunjunganRoute,
  AuthedLaporanRoute: AuthedLaporanRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedAnggotaIdRoute: AuthedAnggotaIdRoute,
  AuthedAnggotaCetakKtaRoute: AuthedAnggotaCetakKtaRoute,
  AuthedAnggotaNewRoute: AuthedAnggotaNewRoute,
  AuthedBukuIdRoute: AuthedBukuIdRoute,
  AuthedBukuNewRoute: AuthedBukuNewRoute,
  AuthedPeminjamanIdRoute: AuthedPeminjamanIdRoute,
  AuthedPeminjamanNewRoute: AuthedPeminjamanNewRoute,
  AuthedAnggotaIndexRoute: AuthedAnggotaIndexRoute,
  AuthedBukuIndexRoute: AuthedBukuIndexRoute,
  AuthedPeminjamanIndexRoute: AuthedPeminjamanIndexRoute,
  AuthedPengembalianIndexRoute: AuthedPengembalianIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
