import type { KtaField, KtaLayout } from '@/lib/kta';

/**
 * Preset library for v1.0.5 #10. Ten original layouts inspired by common
 * Indonesian school KTA conventions (banner header + photo + identity
 * fields + QR), each varying along three orthogonal axes:
 *
 * 1. **Decoration** — flat / accent stripe / diagonal sash / left rail.
 * 2. **Photo placement** — left, right, center, banner-overlay.
 * 3. **Palette** — slate, teal, navy, maroon, emerald, indigo, gold,
 *    rose, amber, cyan.
 *
 * Each preset is a self-contained `KtaLayout` (CR-80, 85.6 × 53.98 mm)
 * with `rect` decorations rendered first so they sit behind text and
 * photo. The layouts are intentionally not personalised — operators are
 * expected to "Pilih dari Galeri" then tweak the colours / fields to
 * match their school via the existing `TemplateEditor`. None of the
 * designs are copied from a third-party source; they are reusable
 * arrangements of the same underlying primitives the editor already
 * exposes.
 */

export interface KtaPreset {
  /** URL-safe stable id (used as React key + i18n key suffix). */
  id: string;
  /** Display name shown in the gallery card. */
  nama: string;
  /** One-line tagline shown beneath the name. */
  deskripsi: string;
  layout: KtaLayout;
}

const CARD_W = 85.6;
const CARD_H = 53.98;

function blank(fields: KtaField[], background = '#ffffff'): KtaLayout {
  return { widthMm: CARD_W, heightMm: CARD_H, background, fields };
}

const klasikPolos: KtaLayout = blank(
  [
    {
      id: 'header',
      kind: 'static',
      text: 'KARTU TANDA ANGGOTA',
      x: 4,
      y: 6,
      width: 92,
      height: 8,
      fontSize: 10,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'center',
    },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 14,
      width: 92,
      height: 8,
      fontSize: 8,
      color: '#475569',
      align: 'center',
    },
    { id: 'foto', kind: 'foto', x: 4, y: 26, width: 22, height: 28 },
    {
      id: 'nama',
      kind: 'nama',
      x: 30,
      y: 28,
      width: 50,
      height: 10,
      fontSize: 12,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 30,
      y: 38,
      width: 50,
      height: 6,
      fontSize: 8,
      color: '#334155',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 30,
      y: 44,
      width: 50,
      height: 6,
      fontSize: 8,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 78, y: 28, width: 18, height: 18 },
  ],
  '#ffffff',
);

const stripAtas: KtaLayout = blank(
  [
    {
      id: 'banner',
      kind: 'rect',
      x: 0,
      y: 0,
      width: 100,
      height: 22,
      fill: '#0f766e',
    },
    {
      id: 'header',
      kind: 'static',
      text: 'KARTU ANGGOTA PERPUSTAKAAN',
      x: 4,
      y: 4,
      width: 92,
      height: 7,
      fontSize: 10,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'center',
    },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 12,
      width: 92,
      height: 7,
      fontSize: 8,
      color: '#ccfbf1',
      align: 'center',
    },
    { id: 'foto', kind: 'foto', x: 4, y: 26, width: 24, height: 30 },
    {
      id: 'nama',
      kind: 'nama',
      x: 32,
      y: 26,
      width: 48,
      height: 9,
      fontSize: 12,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 32,
      y: 35,
      width: 48,
      height: 6,
      fontSize: 8,
      color: '#0f766e',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 32,
      y: 41,
      width: 30,
      height: 6,
      fontSize: 8,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 32,
      y: 47,
      width: 30,
      height: 6,
      fontSize: 8,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 80, y: 26, width: 16, height: 16 },
  ],
  '#f8fafc',
);

const sidebarRail: KtaLayout = blank(
  [
    {
      id: 'rail',
      kind: 'rect',
      x: 0,
      y: 0,
      width: 28,
      height: 100,
      fill: '#1e3a8a',
    },
    {
      id: 'foto',
      kind: 'foto',
      x: 4,
      y: 8,
      width: 20,
      height: 26,
    },
    {
      id: 'kodeBadge',
      kind: 'kodeAnggota',
      x: 4,
      y: 38,
      width: 20,
      height: 6,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'center',
    },
    {
      id: 'header',
      kind: 'identitas',
      x: 32,
      y: 6,
      width: 64,
      height: 8,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#1e3a8a',
      align: 'left',
    },
    {
      id: 'subhead',
      kind: 'static',
      text: 'KARTU TANDA ANGGOTA',
      x: 32,
      y: 14,
      width: 64,
      height: 6,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'nama',
      kind: 'nama',
      x: 32,
      y: 26,
      width: 64,
      height: 9,
      fontSize: 13,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 32,
      y: 36,
      width: 30,
      height: 6,
      fontSize: 8,
      color: '#1e3a8a',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 32,
      y: 42,
      width: 40,
      height: 6,
      fontSize: 8,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 78, y: 32, width: 18, height: 18 },
  ],
  '#ffffff',
);

const minimalisModern: KtaLayout = blank(
  [
    {
      id: 'underline',
      kind: 'rect',
      x: 4,
      y: 22,
      width: 92,
      height: 0.5,
      fill: '#94a3b8',
    },
    {
      id: 'header',
      kind: 'identitas',
      x: 4,
      y: 6,
      width: 92,
      height: 7,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'subhead',
      kind: 'static',
      text: 'Member Card',
      x: 4,
      y: 14,
      width: 92,
      height: 5,
      fontSize: 7,
      color: '#94a3b8',
      align: 'left',
    },
    { id: 'foto', kind: 'foto', x: 4, y: 28, width: 24, height: 24 },
    {
      id: 'nama',
      kind: 'nama',
      x: 32,
      y: 30,
      width: 50,
      height: 8,
      fontSize: 11,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 32,
      y: 38,
      width: 50,
      height: 5,
      fontSize: 7,
      color: '#64748b',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 32,
      y: 44,
      width: 50,
      height: 5,
      fontSize: 7,
      color: '#64748b',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 80, y: 32, width: 16, height: 16 },
  ],
  '#ffffff',
);

const sashDiagonal: KtaLayout = blank(
  [
    // Faux diagonal — three stacked rects of decreasing height to mimic
    // a slash without needing SVG support.
    { id: 'sash1', kind: 'rect', x: 0, y: 0, width: 100, height: 8, fill: '#9f1239' },
    { id: 'sash2', kind: 'rect', x: 0, y: 8, width: 78, height: 6, fill: '#be123c' },
    { id: 'sash3', kind: 'rect', x: 0, y: 14, width: 56, height: 4, fill: '#e11d48' },
    {
      id: 'header',
      kind: 'static',
      text: 'KARTU ANGGOTA',
      x: 4,
      y: 1,
      width: 92,
      height: 6,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'left',
    },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 22,
      width: 92,
      height: 6,
      fontSize: 8,
      color: '#475569',
      align: 'left',
    },
    { id: 'foto', kind: 'foto', x: 4, y: 30, width: 22, height: 22 },
    {
      id: 'nama',
      kind: 'nama',
      x: 30,
      y: 30,
      width: 48,
      height: 9,
      fontSize: 12,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 30,
      y: 39,
      width: 48,
      height: 5,
      fontSize: 8,
      color: '#9f1239',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 30,
      y: 44,
      width: 48,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 78, y: 30, width: 18, height: 18 },
  ],
  '#fff1f2',
);

const portraitTengah: KtaLayout = blank(
  [
    {
      id: 'topBand',
      kind: 'rect',
      x: 0,
      y: 0,
      width: 100,
      height: 8,
      fill: '#047857',
    },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 1,
      width: 92,
      height: 6,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'center',
    },
    {
      id: 'fotoFrame',
      kind: 'rect',
      x: 36,
      y: 12,
      width: 28,
      height: 24,
      fill: '#ecfdf5',
      radius: 1,
    },
    { id: 'foto', kind: 'foto', x: 37, y: 13, width: 26, height: 22 },
    {
      id: 'nama',
      kind: 'nama',
      x: 4,
      y: 38,
      width: 92,
      height: 7,
      fontSize: 11,
      fontWeight: 'bold',
      color: '#064e3b',
      align: 'center',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 4,
      y: 45,
      width: 92,
      height: 5,
      fontSize: 7,
      color: '#065f46',
      align: 'center',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 4,
      y: 50,
      width: 92,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'center',
    },
    { id: 'qr', kind: 'qr', x: 4, y: 12, width: 16, height: 16 },
  ],
  '#f0fdf4',
);

const tradisional: KtaLayout = blank(
  [
    { id: 'border', kind: 'rect', x: 1, y: 1, width: 98, height: 98, fill: '#fef3c7' },
    { id: 'borderInner', kind: 'rect', x: 3, y: 3, width: 94, height: 94, fill: '#ffffff' },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 6,
      width: 92,
      height: 6,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#92400e',
      align: 'center',
    },
    {
      id: 'header',
      kind: 'static',
      text: 'KARTU TANDA ANGGOTA PERPUSTAKAAN',
      x: 4,
      y: 12,
      width: 92,
      height: 5,
      fontSize: 7,
      color: '#78350f',
      align: 'center',
    },
    { id: 'foto', kind: 'foto', x: 6, y: 22, width: 22, height: 28 },
    {
      id: 'nama',
      kind: 'nama',
      x: 32,
      y: 24,
      width: 48,
      height: 8,
      fontSize: 11,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 32,
      y: 32,
      width: 48,
      height: 5,
      fontSize: 8,
      color: '#92400e',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 32,
      y: 38,
      width: 48,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 32,
      y: 43,
      width: 48,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 78, y: 32, width: 16, height: 16 },
  ],
  '#fef3c7',
);

const pelajarModern: KtaLayout = blank(
  [
    {
      id: 'headerBg',
      kind: 'rect',
      x: 0,
      y: 0,
      width: 100,
      height: 18,
      fill: '#4f46e5',
    },
    {
      id: 'fotoBadge',
      kind: 'rect',
      x: 4,
      y: 12,
      width: 22,
      height: 28,
      fill: '#ffffff',
      radius: 1,
    },
    { id: 'foto', kind: 'foto', x: 5, y: 13, width: 20, height: 26 },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 30,
      y: 4,
      width: 66,
      height: 6,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'left',
    },
    {
      id: 'subhead',
      kind: 'static',
      text: 'KARTU PELAJAR / ANGGOTA PERPUSTAKAAN',
      x: 30,
      y: 10,
      width: 66,
      height: 5,
      fontSize: 6,
      color: '#c7d2fe',
      align: 'left',
    },
    {
      id: 'nama',
      kind: 'nama',
      x: 30,
      y: 22,
      width: 66,
      height: 8,
      fontSize: 11,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 30,
      y: 30,
      width: 66,
      height: 5,
      fontSize: 7,
      color: '#4f46e5',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 30,
      y: 35,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 60,
      y: 35,
      width: 36,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 78, y: 42, width: 18, height: 10 },
  ],
  '#ffffff',
);

const emasEksklusif: KtaLayout = blank(
  [
    { id: 'bg', kind: 'rect', x: 0, y: 0, width: 100, height: 100, fill: '#0c0a09' },
    { id: 'topBand', kind: 'rect', x: 0, y: 0, width: 100, height: 4, fill: '#d4af37' },
    { id: 'bottomBand', kind: 'rect', x: 0, y: 96, width: 100, height: 4, fill: '#d4af37' },
    { id: 'fotoFrame', kind: 'rect', x: 4, y: 14, width: 24, height: 30, fill: '#d4af37' },
    { id: 'foto', kind: 'foto', x: 5, y: 15, width: 22, height: 28 },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 7,
      width: 92,
      height: 5,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#d4af37',
      align: 'center',
    },
    {
      id: 'nama',
      kind: 'nama',
      x: 32,
      y: 16,
      width: 64,
      height: 8,
      fontSize: 13,
      fontWeight: 'bold',
      color: '#fef3c7',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 32,
      y: 26,
      width: 64,
      height: 5,
      fontSize: 8,
      color: '#d4af37',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 32,
      y: 32,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#fcd34d',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 62,
      y: 32,
      width: 34,
      height: 5,
      fontSize: 7,
      color: '#fcd34d',
      align: 'left',
    },
    {
      id: 'subhead',
      kind: 'static',
      text: 'PERPUSTAKAAN — KARTU ANGGOTA',
      x: 32,
      y: 40,
      width: 64,
      height: 4,
      fontSize: 6,
      color: '#fde68a',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 76, y: 46, width: 18, height: 18 },
  ],
  '#0c0a09',
);

const qrForward: KtaLayout = blank(
  [
    {
      id: 'leftPanel',
      kind: 'rect',
      x: 0,
      y: 0,
      width: 56,
      height: 100,
      fill: '#ffffff',
    },
    {
      id: 'rightPanel',
      kind: 'rect',
      x: 56,
      y: 0,
      width: 44,
      height: 100,
      fill: '#0891b2',
    },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 6,
      width: 50,
      height: 6,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#0e7490',
      align: 'left',
    },
    { id: 'foto', kind: 'foto', x: 4, y: 16, width: 18, height: 22 },
    {
      id: 'nama',
      kind: 'nama',
      x: 24,
      y: 16,
      width: 30,
      height: 8,
      fontSize: 10,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 24,
      y: 24,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#0e7490',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 24,
      y: 29,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'qrLabel',
      kind: 'static',
      text: 'Pindai untuk peminjaman',
      x: 58,
      y: 6,
      width: 40,
      height: 6,
      fontSize: 6,
      color: '#cffafe',
      align: 'center',
    },
    { id: 'qr', kind: 'qr', x: 64, y: 14, width: 28, height: 28 },
    {
      id: 'qrCaption',
      kind: 'kodeAnggota',
      x: 58,
      y: 44,
      width: 40,
      height: 5,
      fontSize: 7,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'center',
    },
  ],
  '#ffffff',
);

const dwiBahasa: KtaLayout = blank(
  [
    { id: 'topPanel', kind: 'rect', x: 0, y: 0, width: 100, height: 12, fill: '#0f172a' },
    { id: 'underline', kind: 'rect', x: 4, y: 50, width: 92, height: 0.4, fill: '#cbd5e1' },
    {
      id: 'headerId',
      kind: 'static',
      text: 'KARTU TANDA ANGGOTA',
      x: 4,
      y: 2,
      width: 92,
      height: 5,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'left',
    },
    {
      id: 'headerEn',
      kind: 'static',
      text: 'LIBRARY MEMBER CARD',
      x: 4,
      y: 7,
      width: 92,
      height: 4,
      fontSize: 6,
      color: '#94a3b8',
      align: 'left',
    },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 16,
      width: 92,
      height: 5,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    { id: 'foto', kind: 'foto', x: 4, y: 26, width: 22, height: 22 },
    {
      id: 'nama',
      kind: 'nama',
      x: 30,
      y: 26,
      width: 50,
      height: 7,
      fontSize: 11,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 30,
      y: 33,
      width: 50,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 30,
      y: 38,
      width: 50,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'agama',
      kind: 'agama',
      x: 30,
      y: 43,
      width: 50,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 80, y: 28, width: 16, height: 16 },
  ],
  '#ffffff',
);

export const KTA_PRESETS: KtaPreset[] = [
  {
    id: 'klasik-polos',
    nama: 'Klasik Polos',
    deskripsi: 'Layout default — header tengah, foto kiri, QR kanan.',
    layout: klasikPolos,
  },
  {
    id: 'strip-atas-teal',
    nama: 'Strip Atas Teal',
    deskripsi: 'Banner teal di atas, identitas putih, fields kanan.',
    layout: stripAtas,
  },
  {
    id: 'sidebar-rail-navy',
    nama: 'Sidebar Rail Navy',
    deskripsi: 'Rail kiri navy untuk foto, fields fokus di kanan.',
    layout: sidebarRail,
  },
  {
    id: 'minimalis-modern',
    nama: 'Minimalis Modern',
    deskripsi: 'Putih bersih dengan garis bawah aksen, tanpa banner.',
    layout: minimalisModern,
  },
  {
    id: 'sash-diagonal-rose',
    nama: 'Sash Diagonal Rose',
    deskripsi: 'Sash bertingkat rose di atas, vibe energik.',
    layout: sashDiagonal,
  },
  {
    id: 'portrait-tengah-emerald',
    nama: 'Portrait Tengah Emerald',
    deskripsi: 'Foto besar di tengah, fields di bawah, vibe formal.',
    layout: portraitTengah,
  },
  {
    id: 'tradisional-amber',
    nama: 'Tradisional Amber',
    deskripsi: 'Bingkai amber, kesan klasik perpustakaan sekolah.',
    layout: tradisional,
  },
  {
    id: 'pelajar-modern-indigo',
    nama: 'Pelajar Modern Indigo',
    deskripsi: 'Header indigo + foto-badge, kelas + jurusan menonjol.',
    layout: pelajarModern,
  },
  {
    id: 'emas-eksklusif-gold',
    nama: 'Emas Eksklusif',
    deskripsi: 'Hitam pekat + aksen emas, untuk anggota istimewa.',
    layout: emasEksklusif,
  },
  {
    id: 'qr-forward-cyan',
    nama: 'QR Forward Cyan',
    deskripsi: 'Panel QR besar di kanan untuk self-checkout cepat.',
    layout: qrForward,
  },
];

// Bilingual variant kept available for advanced users — surfaced via the
// gallery's "Lainnya" group when we add categorisation in a future cycle.
// Exported so consumers (and the unit suite) can reach every preset that
// ships with the binary, even the ones that aren't on the default 10.
export const KTA_PRESETS_EXTRA: KtaPreset[] = [
  {
    id: 'dwi-bahasa-slate',
    nama: 'Dwi-bahasa Slate',
    deskripsi: 'Header bilingual ID/EN, fields lengkap termasuk agama.',
    layout: dwiBahasa,
  },
];

export function getPresetById(id: string): KtaPreset | undefined {
  return [...KTA_PRESETS, ...KTA_PRESETS_EXTRA].find((p) => p.id === id);
}
