import type { KtaField, KtaLayout } from '@/lib/kta';

/**
 * Preset library for v1.0.5 #10. Ten original layouts inspired by common
 * Indonesian school KTA conventions (banner header + photo + identity
 * fields + QR), each varying along three orthogonal axes:
 *
 * 1. **Decoration** — flat / accent stripe / diagonal sash / left rail.
 * 2. **Photo placement** — left, right, center, banner-overlay.
 * 3. **Palette** — slate, teal, navy, maroon, emerald, indigo, gold,
 *    rose, amber, cyan.
 *
 * Each preset is a self-contained `KtaLayout` (CR-80, 85.6 × 53.98 mm)
 * with `rect` decorations rendered first so they sit behind text and
 * photo. The layouts are intentionally not personalised — operators are
 * expected to "Pilih dari Galeri" then tweak the colours / fields to
 * match their school via the existing `TemplateEditor`. None of the
 * designs are copied from a third-party source; they are reusable
 * arrangements of the same underlying primitives the editor already
 * exposes.
 */

export interface KtaPreset {
  /** URL-safe stable id (used as React key + i18n key suffix). */
  id: string;
  /** Display name shown in the gallery card. */
  nama: string;
  /** One-line tagline shown beneath the name. */
  deskripsi: string;
  layout: KtaLayout;
}

const CARD_W = 85.6;
const CARD_H = 53.98;

function blank(fields: KtaField[], background = '#ffffff'): KtaLayout {
  return { widthMm: CARD_W, heightMm: CARD_H, background, fields };
}

const klasikPolos: KtaLayout = blank(
  [
    {
      id: 'header',
      kind: 'static',
      text: 'KARTU TANDA ANGGOTA',
      x: 4,
      y: 6,
      width: 92,
      height: 8,
      fontSize: 10,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'center',
    },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 14,
      width: 92,
      height: 8,
      fontSize: 8,
      color: '#475569',
      align: 'center',
    },
    { id: 'foto', kind: 'foto', x: 4, y: 26, width: 22, height: 28 },
    {
      id: 'nama',
      kind: 'nama',
      x: 30,
      y: 28,
      width: 50,
      height: 10,
      fontSize: 12,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 30,
      y: 38,
      width: 50,
      height: 6,
      fontSize: 8,
      color: '#334155',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 30,
      y: 44,
      width: 50,
      height: 6,
      fontSize: 8,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 78, y: 28, width: 18, height: 18 },
  ],
  '#ffffff',
);

const stripAtas: KtaLayout = blank(
  [
    {
      id: 'banner',
      kind: 'rect',
      x: 0,
      y: 0,
      width: 100,
      height: 22,
      fill: '#0f766e',
    },
    {
      id: 'header',
      kind: 'static',
      text: 'KARTU ANGGOTA PERPUSTAKAAN',
      x: 4,
      y: 4,
      width: 92,
      height: 7,
      fontSize: 10,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'center',
    },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 12,
      width: 92,
      height: 7,
      fontSize: 8,
      color: '#ccfbf1',
      align: 'center',
    },
    { id: 'foto', kind: 'foto', x: 4, y: 26, width: 24, height: 30 },
    {
      id: 'nama',
      kind: 'nama',
      x: 32,
      y: 26,
      width: 48,
      height: 9,
      fontSize: 12,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 32,
      y: 35,
      width: 48,
      height: 6,
      fontSize: 8,
      color: '#0f766e',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 32,
      y: 41,
      width: 30,
      height: 6,
      fontSize: 8,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 32,
      y: 47,
      width: 30,
      height: 6,
      fontSize: 8,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 80, y: 26, width: 16, height: 16 },
  ],
  '#f8fafc',
);

const sidebarRail: KtaLayout = blank(
  [
    {
      id: 'rail',
      kind: 'rect',
      x: 0,
      y: 0,
      width: 28,
      height: 100,
      fill: '#1e3a8a',
    },
    {
      id: 'foto',
      kind: 'foto',
      x: 4,
      y: 8,
      width: 20,
      height: 26,
    },
    {
      id: 'kodeBadge',
      kind: 'kodeAnggota',
      x: 4,
      y: 38,
      width: 20,
      height: 6,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'center',
    },
    {
      id: 'header',
      kind: 'identitas',
      x: 32,
      y: 6,
      width: 64,
      height: 8,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#1e3a8a',
      align: 'left',
    },
    {
      id: 'subhead',
      kind: 'static',
      text: 'KARTU TANDA ANGGOTA',
      x: 32,
      y: 14,
      width: 64,
      height: 6,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'nama',
      kind: 'nama',
      x: 32,
      y: 26,
      width: 64,
      height: 9,
      fontSize: 13,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 32,
      y: 36,
      width: 30,
      height: 6,
      fontSize: 8,
      color: '#1e3a8a',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 32,
      y: 42,
      width: 40,
      height: 6,
      fontSize: 8,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 78, y: 32, width: 18, height: 18 },
  ],
  '#ffffff',
);

const minimalisModern: KtaLayout = blank(
  [
    {
      id: 'underline',
      kind: 'rect',
      x: 4,
      y: 22,
      width: 92,
      height: 0.5,
      fill: '#94a3b8',
    },
    {
      id: 'header',
      kind: 'identitas',
      x: 4,
      y: 6,
      width: 92,
      height: 7,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'subhead',
      kind: 'static',
      text: 'Member Card',
      x: 4,
      y: 14,
      width: 92,
      height: 5,
      fontSize: 7,
      color: '#94a3b8',
      align: 'left',
    },
    { id: 'foto', kind: 'foto', x: 4, y: 28, width: 24, height: 24 },
    {
      id: 'nama',
      kind: 'nama',
      x: 32,
      y: 30,
      width: 50,
      height: 8,
      fontSize: 11,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 32,
      y: 38,
      width: 50,
      height: 5,
      fontSize: 7,
      color: '#64748b',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 32,
      y: 44,
      width: 50,
      height: 5,
      fontSize: 7,
      color: '#64748b',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 80, y: 32, width: 16, height: 16 },
  ],
  '#ffffff',
);

const sashDiagonal: KtaLayout = blank(
  [
    // Faux diagonal — three stacked rects of decreasing height to mimic
    // a slash without needing SVG support.
    { id: 'sash1', kind: 'rect', x: 0, y: 0, width: 100, height: 8, fill: '#9f1239' },
    { id: 'sash2', kind: 'rect', x: 0, y: 8, width: 78, height: 6, fill: '#be123c' },
    { id: 'sash3', kind: 'rect', x: 0, y: 14, width: 56, height: 4, fill: '#e11d48' },
    {
      id: 'header',
      kind: 'static',
      text: 'KARTU ANGGOTA',
      x: 4,
      y: 1,
      width: 92,
      height: 6,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'left',
    },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 22,
      width: 92,
      height: 6,
      fontSize: 8,
      color: '#475569',
      align: 'left',
    },
    { id: 'foto', kind: 'foto', x: 4, y: 30, width: 22, height: 22 },
    {
      id: 'nama',
      kind: 'nama',
      x: 30,
      y: 30,
      width: 48,
      height: 9,
      fontSize: 12,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 30,
      y: 39,
      width: 48,
      height: 5,
      fontSize: 8,
      color: '#9f1239',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 30,
      y: 44,
      width: 48,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 78, y: 30, width: 18, height: 18 },
  ],
  '#fff1f2',
);

const portraitTengah: KtaLayout = blank(
  [
    {
      id: 'topBand',
      kind: 'rect',
      x: 0,
      y: 0,
      width: 100,
      height: 8,
      fill: '#047857',
    },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 1,
      width: 92,
      height: 6,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'center',
    },
    {
      id: 'fotoFrame',
      kind: 'rect',
      x: 36,
      y: 12,
      width: 28,
      height: 24,
      fill: '#ecfdf5',
      radius: 1,
    },
    { id: 'foto', kind: 'foto', x: 37, y: 13, width: 26, height: 22 },
    {
      id: 'nama',
      kind: 'nama',
      x: 4,
      y: 38,
      width: 92,
      height: 7,
      fontSize: 11,
      fontWeight: 'bold',
      color: '#064e3b',
      align: 'center',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 4,
      y: 45,
      width: 92,
      height: 5,
      fontSize: 7,
      color: '#065f46',
      align: 'center',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 4,
      y: 50,
      width: 92,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'center',
    },
    { id: 'qr', kind: 'qr', x: 4, y: 12, width: 16, height: 16 },
  ],
  '#f0fdf4',
);

const tradisional: KtaLayout = blank(
  [
    { id: 'border', kind: 'rect', x: 1, y: 1, width: 98, height: 98, fill: '#fef3c7' },
    { id: 'borderInner', kind: 'rect', x: 3, y: 3, width: 94, height: 94, fill: '#ffffff' },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 6,
      width: 92,
      height: 6,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#92400e',
      align: 'center',
    },
    {
      id: 'header',
      kind: 'static',
      text: 'KARTU TANDA ANGGOTA PERPUSTAKAAN',
      x: 4,
      y: 12,
      width: 92,
      height: 5,
      fontSize: 7,
      color: '#78350f',
      align: 'center',
    },
    { id: 'foto', kind: 'foto', x: 6, y: 22, width: 22, height: 28 },
    {
      id: 'nama',
      kind: 'nama',
      x: 32,
      y: 24,
      width: 48,
      height: 8,
      fontSize: 11,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 32,
      y: 32,
      width: 48,
      height: 5,
      fontSize: 8,
      color: '#92400e',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 32,
      y: 38,
      width: 48,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 32,
      y: 43,
      width: 48,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 78, y: 32, width: 16, height: 16 },
  ],
  '#fef3c7',
);

const pelajarModern: KtaLayout = blank(
  [
    {
      id: 'headerBg',
      kind: 'rect',
      x: 0,
      y: 0,
      width: 100,
      height: 18,
      fill: '#4f46e5',
    },
    {
      id: 'fotoBadge',
      kind: 'rect',
      x: 4,
      y: 12,
      width: 22,
      height: 28,
      fill: '#ffffff',
      radius: 1,
    },
    { id: 'foto', kind: 'foto', x: 5, y: 13, width: 20, height: 26 },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 30,
      y: 4,
      width: 66,
      height: 6,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'left',
    },
    {
      id: 'subhead',
      kind: 'static',
      text: 'KARTU PELAJAR / ANGGOTA PERPUSTAKAAN',
      x: 30,
      y: 10,
      width: 66,
      height: 5,
      fontSize: 6,
      color: '#c7d2fe',
      align: 'left',
    },
    {
      id: 'nama',
      kind: 'nama',
      x: 30,
      y: 22,
      width: 66,
      height: 8,
      fontSize: 11,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 30,
      y: 30,
      width: 66,
      height: 5,
      fontSize: 7,
      color: '#4f46e5',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 30,
      y: 35,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 60,
      y: 35,
      width: 36,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 78, y: 42, width: 18, height: 10 },
  ],
  '#ffffff',
);

const emasEksklusif: KtaLayout = blank(
  [
    { id: 'bg', kind: 'rect', x: 0, y: 0, width: 100, height: 100, fill: '#0c0a09' },
    { id: 'topBand', kind: 'rect', x: 0, y: 0, width: 100, height: 4, fill: '#d4af37' },
    { id: 'bottomBand', kind: 'rect', x: 0, y: 96, width: 100, height: 4, fill: '#d4af37' },
    { id: 'fotoFrame', kind: 'rect', x: 4, y: 14, width: 24, height: 30, fill: '#d4af37' },
    { id: 'foto', kind: 'foto', x: 5, y: 15, width: 22, height: 28 },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 7,
      width: 92,
      height: 5,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#d4af37',
      align: 'center',
    },
    {
      id: 'nama',
      kind: 'nama',
      x: 32,
      y: 16,
      width: 64,
      height: 8,
      fontSize: 13,
      fontWeight: 'bold',
      color: '#fef3c7',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 32,
      y: 26,
      width: 64,
      height: 5,
      fontSize: 8,
      color: '#d4af37',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 32,
      y: 32,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#fcd34d',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 62,
      y: 32,
      width: 34,
      height: 5,
      fontSize: 7,
      color: '#fcd34d',
      align: 'left',
    },
    {
      id: 'subhead',
      kind: 'static',
      text: 'PERPUSTAKAAN — KARTU ANGGOTA',
      x: 32,
      y: 40,
      width: 64,
      height: 4,
      fontSize: 6,
      color: '#fde68a',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 76, y: 46, width: 18, height: 18 },
  ],
  '#0c0a09',
);

const qrForward: KtaLayout = blank(
  [
    {
      id: 'leftPanel',
      kind: 'rect',
      x: 0,
      y: 0,
      width: 56,
      height: 100,
      fill: '#ffffff',
    },
    {
      id: 'rightPanel',
      kind: 'rect',
      x: 56,
      y: 0,
      width: 44,
      height: 100,
      fill: '#0891b2',
    },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 6,
      width: 50,
      height: 6,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#0e7490',
      align: 'left',
    },
    { id: 'foto', kind: 'foto', x: 4, y: 16, width: 18, height: 22 },
    {
      id: 'nama',
      kind: 'nama',
      x: 24,
      y: 16,
      width: 30,
      height: 8,
      fontSize: 10,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 24,
      y: 24,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#0e7490',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 24,
      y: 29,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'qrLabel',
      kind: 'static',
      text: 'Pindai untuk peminjaman',
      x: 58,
      y: 6,
      width: 40,
      height: 6,
      fontSize: 6,
      color: '#cffafe',
      align: 'center',
    },
    { id: 'qr', kind: 'qr', x: 64, y: 14, width: 28, height: 28 },
    {
      id: 'qrCaption',
      kind: 'kodeAnggota',
      x: 58,
      y: 44,
      width: 40,
      height: 5,
      fontSize: 7,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'center',
    },
  ],
  '#ffffff',
);

const dwiBahasa: KtaLayout = blank(
  [
    { id: 'topPanel', kind: 'rect', x: 0, y: 0, width: 100, height: 12, fill: '#0f172a' },
    { id: 'underline', kind: 'rect', x: 4, y: 50, width: 92, height: 0.4, fill: '#cbd5e1' },
    {
      id: 'headerId',
      kind: 'static',
      text: 'KARTU TANDA ANGGOTA',
      x: 4,
      y: 2,
      width: 92,
      height: 5,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'left',
    },
    {
      id: 'headerEn',
      kind: 'static',
      text: 'LIBRARY MEMBER CARD',
      x: 4,
      y: 7,
      width: 92,
      height: 4,
      fontSize: 6,
      color: '#94a3b8',
      align: 'left',
    },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 16,
      width: 92,
      height: 5,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    { id: 'foto', kind: 'foto', x: 4, y: 26, width: 22, height: 22 },
    {
      id: 'nama',
      kind: 'nama',
      x: 30,
      y: 26,
      width: 50,
      height: 7,
      fontSize: 11,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 30,
      y: 33,
      width: 50,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 30,
      y: 38,
      width: 50,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'agama',
      kind: 'agama',
      x: 30,
      y: 43,
      width: 50,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 80, y: 28, width: 16, height: 16 },
  ],
  '#ffffff',
);

// FEAT-16 — 10 preset baru (v1.0.8). Setiap preset disusun dengan helper
// `blank` yang sama dan memenuhi acceptance test `ktaPresets.test.ts`:
// foto + qr + identitas + nama + kodeAnggota present, semua field 0..100,
// fontSize 5..16, rect fill hex, ID unik di dalam preset.

const ichasoftKlasikBlue: KtaLayout = blank(
  [
    { id: 'banner', kind: 'rect', x: 0, y: 0, width: 100, height: 18, fill: '#0c4a6e' },
    { id: 'accent', kind: 'rect', x: 0, y: 18, width: 100, height: 1.5, fill: '#0ea5e9' },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 4,
      width: 92,
      height: 5,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'center',
    },
    {
      id: 'subhead',
      kind: 'static',
      text: 'KARTU TANDA ANGGOTA',
      x: 4,
      y: 10,
      width: 92,
      height: 5,
      fontSize: 7,
      color: '#bae6fd',
      align: 'center',
    },
    { id: 'foto', kind: 'foto', x: 5, y: 24, width: 22, height: 28 },
    {
      id: 'nama',
      kind: 'nama',
      x: 31,
      y: 24,
      width: 64,
      height: 8,
      fontSize: 12,
      fontWeight: 'bold',
      color: '#0c4a6e',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 31,
      y: 33,
      width: 64,
      height: 5,
      fontSize: 8,
      color: '#0369a1',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 31,
      y: 39,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 61,
      y: 39,
      width: 34,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 78, y: 44, width: 16, height: 8 },
  ],
  '#ffffff',
);

const simpleFlatCoral: KtaLayout = blank(
  [
    { id: 'topRail', kind: 'rect', x: 0, y: 0, width: 100, height: 6, fill: '#fb7185' },
    { id: 'leftBlock', kind: 'rect', x: 0, y: 6, width: 32, height: 94, fill: '#fff1f2' },
    { id: 'foto', kind: 'foto', x: 5, y: 12, width: 22, height: 28 },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 35,
      y: 10,
      width: 60,
      height: 6,
      fontSize: 8,
      fontWeight: 'bold',
      color: '#9f1239',
      align: 'left',
    },
    {
      id: 'nama',
      kind: 'nama',
      x: 35,
      y: 18,
      width: 60,
      height: 8,
      fontSize: 11,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 35,
      y: 27,
      width: 60,
      height: 5,
      fontSize: 7,
      color: '#fb7185',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 35,
      y: 33,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#64748b',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 35,
      y: 39,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#64748b',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 78, y: 32, width: 18, height: 18 },
  ],
  '#ffffff',
);

const corporateGreyMonochrome: KtaLayout = blank(
  [
    { id: 'header', kind: 'rect', x: 0, y: 0, width: 100, height: 14, fill: '#374151' },
    { id: 'shadow', kind: 'rect', x: 0, y: 14, width: 100, height: 1, fill: '#9ca3af' },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 4,
      width: 92,
      height: 7,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#f9fafb',
      align: 'center',
    },
    { id: 'fotoFrame', kind: 'rect', x: 4, y: 20, width: 24, height: 30, fill: '#e5e7eb' },
    { id: 'foto', kind: 'foto', x: 5, y: 21, width: 22, height: 28 },
    {
      id: 'nama',
      kind: 'nama',
      x: 32,
      y: 22,
      width: 64,
      height: 8,
      fontSize: 12,
      fontWeight: 'bold',
      color: '#111827',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 32,
      y: 31,
      width: 64,
      height: 5,
      fontSize: 8,
      color: '#374151',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 32,
      y: 37,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#6b7280',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 62,
      y: 37,
      width: 34,
      height: 5,
      fontSize: 7,
      color: '#6b7280',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 80, y: 44, width: 14, height: 8 },
  ],
  '#f9fafb',
);

const gradientSunsetPurple: KtaLayout = blank(
  [
    { id: 'g1', kind: 'rect', x: 0, y: 0, width: 100, height: 6, fill: '#4c1d95' },
    { id: 'g2', kind: 'rect', x: 0, y: 6, width: 100, height: 6, fill: '#6d28d9' },
    { id: 'g3', kind: 'rect', x: 0, y: 12, width: 100, height: 6, fill: '#9333ea' },
    { id: 'g4', kind: 'rect', x: 0, y: 18, width: 100, height: 6, fill: '#c084fc' },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 6,
      width: 92,
      height: 6,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'center',
    },
    {
      id: 'subhead',
      kind: 'static',
      text: 'KARTU TANDA ANGGOTA',
      x: 4,
      y: 14,
      width: 92,
      height: 5,
      fontSize: 7,
      color: '#f5d0fe',
      align: 'center',
    },
    { id: 'foto', kind: 'foto', x: 4, y: 28, width: 22, height: 28 },
    {
      id: 'nama',
      kind: 'nama',
      x: 30,
      y: 28,
      width: 64,
      height: 8,
      fontSize: 12,
      fontWeight: 'bold',
      color: '#4c1d95',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 30,
      y: 36,
      width: 64,
      height: 5,
      fontSize: 8,
      color: '#7e22ce',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 30,
      y: 42,
      width: 32,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 80, y: 42, width: 14, height: 10 },
  ],
  '#faf5ff',
);

const waveBottomAqua: KtaLayout = blank(
  [
    { id: 'waveBack', kind: 'rect', x: 0, y: 88, width: 100, height: 12, fill: '#06b6d4' },
    { id: 'waveMid', kind: 'rect', x: 0, y: 80, width: 100, height: 8, fill: '#22d3ee' },
    { id: 'waveTop', kind: 'rect', x: 0, y: 74, width: 100, height: 6, fill: '#a5f3fc' },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 6,
      width: 92,
      height: 6,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#0e7490',
      align: 'center',
    },
    { id: 'foto', kind: 'foto', x: 5, y: 16, width: 24, height: 30 },
    {
      id: 'nama',
      kind: 'nama',
      x: 32,
      y: 18,
      width: 62,
      height: 8,
      fontSize: 12,
      fontWeight: 'bold',
      color: '#0e7490',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 32,
      y: 28,
      width: 62,
      height: 5,
      fontSize: 8,
      color: '#0891b2',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 32,
      y: 34,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 62,
      y: 34,
      width: 32,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 32, y: 41, width: 14, height: 14 },
  ],
  '#ecfeff',
);

const kotakGridMustard: KtaLayout = blank(
  [
    { id: 'topBox', kind: 'rect', x: 0, y: 0, width: 100, height: 4, fill: '#ca8a04' },
    { id: 'sideBoxA', kind: 'rect', x: 0, y: 4, width: 4, height: 96, fill: '#facc15' },
    { id: 'sideBoxB', kind: 'rect', x: 96, y: 4, width: 4, height: 96, fill: '#facc15' },
    { id: 'bottomBox', kind: 'rect', x: 0, y: 96, width: 100, height: 4, fill: '#ca8a04' },
    { id: 'centerBg', kind: 'rect', x: 4, y: 4, width: 92, height: 92, fill: '#fefce8' },
    { id: 'fotoBox', kind: 'rect', x: 6, y: 8, width: 24, height: 30, fill: '#ffffff' },
    { id: 'foto', kind: 'foto', x: 7, y: 9, width: 22, height: 28 },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 32,
      y: 8,
      width: 60,
      height: 6,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#854d0e',
      align: 'left',
    },
    {
      id: 'nama',
      kind: 'nama',
      x: 32,
      y: 16,
      width: 60,
      height: 8,
      fontSize: 12,
      fontWeight: 'bold',
      color: '#1f2937',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 32,
      y: 25,
      width: 60,
      height: 5,
      fontSize: 8,
      color: '#a16207',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 32,
      y: 31,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 78, y: 40, width: 14, height: 14 },
  ],
  '#fefce8',
);

const kartuBatikMerah: KtaLayout = blank(
  [
    { id: 'frame', kind: 'rect', x: 0, y: 0, width: 100, height: 4, fill: '#7f1d1d' },
    { id: 'frameB', kind: 'rect', x: 0, y: 96, width: 100, height: 4, fill: '#7f1d1d' },
    { id: 'sash', kind: 'rect', x: 0, y: 4, width: 100, height: 6, fill: '#dc2626' },
    { id: 'corner1', kind: 'rect', x: 4, y: 12, width: 6, height: 6, fill: '#fef2f2' },
    { id: 'corner2', kind: 'rect', x: 90, y: 12, width: 6, height: 6, fill: '#fef2f2' },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 4,
      width: 92,
      height: 6,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'center',
    },
    { id: 'foto', kind: 'foto', x: 5, y: 22, width: 22, height: 28 },
    {
      id: 'nama',
      kind: 'nama',
      x: 30,
      y: 22,
      width: 66,
      height: 8,
      fontSize: 12,
      fontWeight: 'bold',
      color: '#7f1d1d',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 30,
      y: 32,
      width: 66,
      height: 5,
      fontSize: 8,
      color: '#b91c1c',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 30,
      y: 38,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 60,
      y: 38,
      width: 36,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 78, y: 44, width: 14, height: 8 },
  ],
  '#fef2f2',
);

const vertikalStripMint: KtaLayout = blank(
  [
    { id: 'leftStrip', kind: 'rect', x: 0, y: 0, width: 8, height: 100, fill: '#10b981' },
    { id: 'softBg', kind: 'rect', x: 8, y: 0, width: 92, height: 100, fill: '#ecfdf5' },
    { id: 'foto', kind: 'foto', x: 12, y: 8, width: 22, height: 28 },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 38,
      y: 6,
      width: 58,
      height: 6,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#065f46',
      align: 'left',
    },
    {
      id: 'subhead',
      kind: 'static',
      text: 'KARTU TANDA ANGGOTA',
      x: 38,
      y: 12,
      width: 58,
      height: 5,
      fontSize: 6,
      color: '#10b981',
      align: 'left',
    },
    {
      id: 'nama',
      kind: 'nama',
      x: 38,
      y: 22,
      width: 58,
      height: 8,
      fontSize: 12,
      fontWeight: 'bold',
      color: '#064e3b',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 38,
      y: 32,
      width: 58,
      height: 5,
      fontSize: 8,
      color: '#10b981',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 38,
      y: 38,
      width: 28,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 80, y: 40, width: 14, height: 14 },
  ],
  '#ecfdf5',
);

const polkadotPastelPink: KtaLayout = blank(
  [
    { id: 'bg', kind: 'rect', x: 0, y: 0, width: 100, height: 100, fill: '#fdf2f8' },
    { id: 'd1', kind: 'rect', x: 8, y: 6, width: 4, height: 4, fill: '#fbcfe8', radius: 2 },
    { id: 'd2', kind: 'rect', x: 22, y: 12, width: 3, height: 3, fill: '#f9a8d4', radius: 1.5 },
    { id: 'd3', kind: 'rect', x: 76, y: 8, width: 5, height: 5, fill: '#fbcfe8', radius: 2.5 },
    { id: 'd4', kind: 'rect', x: 88, y: 14, width: 3, height: 3, fill: '#f9a8d4', radius: 1.5 },
    { id: 'd5', kind: 'rect', x: 4, y: 86, width: 4, height: 4, fill: '#fbcfe8', radius: 2 },
    { id: 'd6', kind: 'rect', x: 90, y: 90, width: 3, height: 3, fill: '#f9a8d4', radius: 1.5 },
    { id: 'foto', kind: 'foto', x: 6, y: 22, width: 22, height: 28 },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 6,
      width: 92,
      height: 6,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#9d174d',
      align: 'center',
    },
    {
      id: 'nama',
      kind: 'nama',
      x: 32,
      y: 22,
      width: 62,
      height: 8,
      fontSize: 12,
      fontWeight: 'bold',
      color: '#831843',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 32,
      y: 30,
      width: 62,
      height: 5,
      fontSize: 8,
      color: '#db2777',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 32,
      y: 36,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 80, y: 40, width: 14, height: 12 },
  ],
  '#fdf2f8',
);

const monolineLineArtBlack: KtaLayout = blank(
  [
    { id: 'frameTop', kind: 'rect', x: 0, y: 0, width: 100, height: 1, fill: '#0f172a' },
    { id: 'frameBot', kind: 'rect', x: 0, y: 99, width: 100, height: 1, fill: '#0f172a' },
    { id: 'frameLeft', kind: 'rect', x: 0, y: 0, width: 1, height: 100, fill: '#0f172a' },
    { id: 'frameRight', kind: 'rect', x: 99, y: 0, width: 1, height: 100, fill: '#0f172a' },
    { id: 'innerLine', kind: 'rect', x: 3, y: 3, width: 94, height: 0.4, fill: '#1f2937' },
    { id: 'innerLineB', kind: 'rect', x: 3, y: 96.6, width: 94, height: 0.4, fill: '#1f2937' },
    {
      id: 'identitas',
      kind: 'identitas',
      x: 4,
      y: 5,
      width: 92,
      height: 6,
      fontSize: 9,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'center',
    },
    {
      id: 'subhead',
      kind: 'static',
      text: 'KARTU TANDA ANGGOTA',
      x: 4,
      y: 12,
      width: 92,
      height: 4,
      fontSize: 6,
      color: '#475569',
      align: 'center',
    },
    { id: 'fotoFrame', kind: 'rect', x: 6, y: 22, width: 22, height: 28, fill: '#f8fafc' },
    { id: 'foto', kind: 'foto', x: 6.4, y: 22.4, width: 21.2, height: 27.2 },
    {
      id: 'nama',
      kind: 'nama',
      x: 32,
      y: 22,
      width: 62,
      height: 8,
      fontSize: 12,
      fontWeight: 'bold',
      color: '#0f172a',
      align: 'left',
    },
    {
      id: 'kode',
      kind: 'kodeAnggota',
      x: 32,
      y: 30,
      width: 62,
      height: 5,
      fontSize: 8,
      color: '#1f2937',
      align: 'left',
    },
    {
      id: 'kelas',
      kind: 'kelas',
      x: 32,
      y: 36,
      width: 30,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    {
      id: 'jurusan',
      kind: 'jurusan',
      x: 62,
      y: 36,
      width: 32,
      height: 5,
      fontSize: 7,
      color: '#475569',
      align: 'left',
    },
    { id: 'qr', kind: 'qr', x: 78, y: 42, width: 14, height: 10 },
  ],
  '#ffffff',
);

export const KTA_PRESETS: KtaPreset[] = [
  {
    id: 'klasik-polos',
    nama: 'Klasik Polos',
    deskripsi: 'Layout default — header tengah, foto kiri, QR kanan.',
    layout: klasikPolos,
  },
  {
    id: 'strip-atas-teal',
    nama: 'Strip Atas Teal',
    deskripsi: 'Banner teal di atas, identitas putih, fields kanan.',
    layout: stripAtas,
  },
  {
    id: 'sidebar-rail-navy',
    nama: 'Sidebar Rail Navy',
    deskripsi: 'Rail kiri navy untuk foto, fields fokus di kanan.',
    layout: sidebarRail,
  },
  {
    id: 'minimalis-modern',
    nama: 'Minimalis Modern',
    deskripsi: 'Putih bersih dengan garis bawah aksen, tanpa banner.',
    layout: minimalisModern,
  },
  {
    id: 'sash-diagonal-rose',
    nama: 'Sash Diagonal Rose',
    deskripsi: 'Sash bertingkat rose di atas, vibe energik.',
    layout: sashDiagonal,
  },
  {
    id: 'portrait-tengah-emerald',
    nama: 'Portrait Tengah Emerald',
    deskripsi: 'Foto besar di tengah, fields di bawah, vibe formal.',
    layout: portraitTengah,
  },
  {
    id: 'tradisional-amber',
    nama: 'Tradisional Amber',
    deskripsi: 'Bingkai amber, kesan klasik perpustakaan sekolah.',
    layout: tradisional,
  },
  {
    id: 'pelajar-modern-indigo',
    nama: 'Pelajar Modern Indigo',
    deskripsi: 'Header indigo + foto-badge, kelas + jurusan menonjol.',
    layout: pelajarModern,
  },
  {
    id: 'emas-eksklusif-gold',
    nama: 'Emas Eksklusif',
    deskripsi: 'Hitam pekat + aksen emas, untuk anggota istimewa.',
    layout: emasEksklusif,
  },
  {
    id: 'qr-forward-cyan',
    nama: 'QR Forward Cyan',
    deskripsi: 'Panel QR besar di kanan untuk self-checkout cepat.',
    layout: qrForward,
  },
  {
    id: 'ichasoft-klasik-blue',
    nama: 'Ichasoft Klasik Blue',
    deskripsi: 'Header navy + aksen sky, biodata table, vibe formal.',
    layout: ichasoftKlasikBlue,
  },
  {
    id: 'simple-flat-coral',
    nama: 'Simple Flat Coral',
    deskripsi: 'Flat coral + putih, modern minimal lowercase teks.',
    layout: simpleFlatCoral,
  },
  {
    id: 'corporate-grey-monochrome',
    nama: 'Corporate Grey Monochrome',
    deskripsi: 'Grayscale corporate formal — cocok untuk universitas/SMK.',
    layout: corporateGreyMonochrome,
  },
  {
    id: 'gradient-sunset-purple',
    nama: 'Gradient Sunset Purple',
    deskripsi: 'Banner gradient purple bertingkat, modern playful.',
    layout: gradientSunsetPurple,
  },
  {
    id: 'wave-bottom-aqua',
    nama: 'Wave Bottom Aqua',
    deskripsi: 'Aksen ombak bawah aqua, tropical vibe.',
    layout: waveBottomAqua,
  },
  {
    id: 'kotak-grid-mustard',
    nama: 'Kotak Grid Mustard',
    deskripsi: 'Bingkai kotak mustard + foto hard-edge.',
    layout: kotakGridMustard,
  },
  {
    id: 'kartu-batik-merah',
    nama: 'Kartu Batik Merah',
    deskripsi: 'Sash merah + corner ornament, kesan etnik formal.',
    layout: kartuBatikMerah,
  },
  {
    id: 'vertikal-strip-mint',
    nama: 'Vertikal Strip Mint',
    deskripsi: 'Strip kiri mint, fields vertikal di kanan.',
    layout: vertikalStripMint,
  },
  {
    id: 'polkadot-pastel-pink',
    nama: 'Polkadot Pastel Pink',
    deskripsi: 'Polkadot pastel pink, ramah anak SD/MI.',
    layout: polkadotPastelPink,
  },
  {
    id: 'monoline-line-art-black',
    nama: 'Monoline Line Art Black',
    deskripsi: 'B&W line-art frame minimalis editorial.',
    layout: monolineLineArtBlack,
  },
];

// Bilingual variant kept available for advanced users — surfaced via the
// gallery's "Lainnya" group when we add categorisation in a future cycle.
// Exported so consumers (and the unit suite) can reach every preset that
// ships with the binary, even the ones that aren't on the default 10.
export const KTA_PRESETS_EXTRA: KtaPreset[] = [
  {
    id: 'dwi-bahasa-slate',
    nama: 'Dwi-bahasa Slate',
    deskripsi: 'Header bilingual ID/EN, fields lengkap termasuk agama.',
    layout: dwiBahasa,
  },
];

export function getPresetById(id: string): KtaPreset | undefined {
  return [...KTA_PRESETS, ...KTA_PRESETS_EXTRA].find((p) => p.id === id);
}
